import { EdgeGatewayL2VpnProxySettingsJson } from './__json__/edge-gateway-l2vpn-proxy-settings-json';

/* istanbul ignore next: autogenerated */
export class EdgeGatewayL2VpnProxySettings {

  constructor(private _json: EdgeGatewayL2VpnProxySettingsJson) {
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get address.
   * @returns {string}
   */
  get address(): string {
    return this._json.address;
  }

  /**
   * Get port.
   * @returns {number}
   */
  get port(): number {
    return this._json.port;
  }

  /**
   * Get user name.
   * @returns {string}
   */
  get userName(): string {
    return this._json.user_name;
  }

  /**
   * Get password.
   * @returns {string}
   */
  get password(): string {
    return this._json.password;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayL2VpnProxySettingsJson}
   */
  get json(): EdgeGatewayL2VpnProxySettingsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
