import { EdgeGatewayL2VpnLoggingJson } from './__json__/edge-gateway-l2vpn-logging-json';
import { EdgeGatewayL2VpnSiteJson } from './__json__/edge-gateway-l2vpn-site-json';
import { EdgeGatewayL2VpnUpdateRequestJson } from './__json__/edge-gateway-l2vpn-update-request-json';
import { EdgeGatewayL2VpnLogging } from './edge-gateway-l2vpn-logging';
import { EdgeGatewayL2VpnSite } from './edge-gateway-l2vpn-site';
import { EdgeGatewayL2VpnSiteType } from './edge-gateway-l2vpn-site-type';

/* istanbul ignore next: autogenerated */
export class EdgeGatewayL2VpnUpdateRequest {

  private readonly _json: EdgeGatewayL2VpnUpdateRequestJson;

  constructor(edgeGatewayL2VPNUpdateRequest: EdgeGatewayL2VpnUpdateRequest);
  constructor(edgeGatewayL2VPNUpdateRequestJson: EdgeGatewayL2VpnUpdateRequestJson);
  constructor(enabled: boolean, logging: EdgeGatewayL2VpnLoggingJson,
              l2VpnSiteType: EdgeGatewayL2VpnSiteType,
              l2VpnSite: EdgeGatewayL2VpnSiteJson);
  constructor(firstParam: boolean | EdgeGatewayL2VpnUpdateRequest | EdgeGatewayL2VpnUpdateRequestJson,
              logging?: EdgeGatewayL2VpnLoggingJson,
              l2VpnSiteType?: EdgeGatewayL2VpnSiteType,
              l2VpnSite?: EdgeGatewayL2VpnSiteJson) {
    if (typeof firstParam === 'boolean') {
      // Parameters constructor
      this._json = {
        enabled: firstParam,
        logging: logging,
        l2_vpn_site_type: l2VpnSiteType,
        l2_vpn_site: l2VpnSite
      } as EdgeGatewayL2VpnUpdateRequestJson;
    } else if (firstParam instanceof EdgeGatewayL2VpnUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as EdgeGatewayL2VpnUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as EdgeGatewayL2VpnUpdateRequestJson;
    }
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get logging.
   * @returns {EdgeGatewayL2VpnLogging}
   */
  get logging(): EdgeGatewayL2VpnLogging {
    return new EdgeGatewayL2VpnLogging(this._json.logging);
  }

  /**
   * Get l2 vpn site type.
   * @returns {EdgeGatewayL2VpnSiteType}
   */
  get l2VpnSiteType(): EdgeGatewayL2VpnSiteType {
    return this._json.l2_vpn_site_type;
  }

  /**
   * Get l2 vpn site.
   * @returns {EdgeGatewayL2VpnSite}
   */
  get l2VpnSite(): EdgeGatewayL2VpnSite {
    return new EdgeGatewayL2VpnSite(this._json.l2_vpn_site);
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayL2VpnUpdateRequestJson}
   */
  get json(): EdgeGatewayL2VpnUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
