import { EdgeGatewayL2vpnStatisticsDataJson } from './__json__/edge-gateway-l2vpn-statistics-data-json';
import { EdgeGatewayL2vpnTunnelStatusType } from './edge-gateway-l2vpn-statistics-tunnel-status-type';

/**
 * L2VPN Statistics object
 */
/* istanbul ignore next: autogenerated */
export class EdgeGatewayL2vpnStatisticsData {
  constructor(private _json: EdgeGatewayL2vpnStatisticsDataJson) {}

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get tunnel status.
   * @returns {EdgeGatewayL2vpnTunnelStatusType}
   */
  get tunnelStatus(): EdgeGatewayL2vpnTunnelStatusType {
    return this._json.tunnel_status;
  }

  /**
   * Get established date.
   * @returns {number}
   */
  get establishedDate(): number {
    return this._json.established_date;
  }

  /**
   * Get tx bytes from local subnet.
   * @returns {number}
   */
  get txBytesFromLocalSubnet(): number {
    return this._json.tx_bytes_from_local_subnet;
  }

  /**
   * Get rx bytes on local subnet.
   * @returns {number}
   */
  get rxBytesOnLocalSubnet(): number {
    return this._json.rx_bytes_on_local_subnet;
  }

  /**
   * Get dropped rx packets.
   * @returns {number}
   */
  get droppedRxPackets(): number {
    return this._json.dropped_rx_packets;
  }

  /**
   * Get dropped tx packets.
   * @returns {number}
   */
  get droppedTxPackets(): number {
    return this._json.dropped_tx_packets;
  }

  /**
   * Get failure message.
   * @returns {string}
   */
  get failureMessage(): string {
    return this._json.failure_message;
  }

  /**
   * Get last updated time.
   * @returns {number}
   */
  get lastUpdatedTime(): number {
    return this._json.last_updated_time;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayL2vpnStatisticsDataJson}
   */
  get json(): EdgeGatewayL2vpnStatisticsDataJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
