import { EdgeGatewayL2VpnSiteJson } from './__json__/edge-gateway-l2vpn-site-json';
import { EdgeGatewayL2VpnClient } from './edge-gateway-l2vpn-client';
import { EdgeGatewayL2VpnServer } from './edge-gateway-l2vpn-server';

/* istanbul ignore next: autogenerated */
export class EdgeGatewayL2VpnSite {

  constructor(private _json: EdgeGatewayL2VpnSiteJson) {
  }

  /**
   * Get client.
   * @returns {EdgeGatewayL2VpnClient | undefined}
   */
  get client(): EdgeGatewayL2VpnClient | undefined {
    if (!this._json.client) {
      return undefined;
    }
    return new EdgeGatewayL2VpnClient(this._json.client);
  }

  /**
   * Get server.
   * @returns {EdgeGatewayL2VpnServer | undefined}
   */
  get server(): EdgeGatewayL2VpnServer | undefined {
    if (!this._json.server) {
      return undefined;
    }
    return new EdgeGatewayL2VpnServer(this._json.server);
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayL2VpnSiteJson}
   */
  get json(): EdgeGatewayL2VpnSiteJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
