import { BillingReportRequestJson, ReportType } from './__json__';

/* istanbul ignore next: autogenerated */
export class BillingReportRequest {

  private readonly _json: BillingReportRequestJson;

  constructor(billingReportRequest: BillingReportRequest);
  constructor(billingReportRequestJson: BillingReportRequestJson);
  constructor(customColumns: { [key: string]: string }, rows: Array<string>, date: number, email: string,
              filename: string, type: ReportType);
  constructor(firstParam: { [key: string]: string } | BillingReportRequest | BillingReportRequestJson,
              rows?: Array<string>, date?: number, email?: string, filename?: string, type?: ReportType) {
    if (firstParam && rows) {
      // Parameters constructor
      this._json = {
        custom_columns: firstParam,
        rows: rows,
        date: date,
        email: email,
        filename: filename,
        type: type
      } as BillingReportRequestJson;
    } else if (firstParam instanceof BillingReportRequest) {
      // Copy constructor
      this._json = (firstParam as BillingReportRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as BillingReportRequestJson;
    }
  }

  /**
   * Get custom columns.
   * @returns {{ [key: string]: string }}
   */
  get customColumns(): { [key: string]: string } {
    return this._json.custom_columns;
  }

  /**
   * Get rows.
   * @returns {Array<string>}
   */
  get rows(): Array<string> {
    return this._json.rows;
  }

  /**
   * Get date.
   * @returns {number}
   */
  get date(): number {
    return this._json.date;
  }

  /**
   * Get email.
   * @returns {string}
   */
  get email(): string {
    return this._json.email;
  }

  /**
   * Get filename.
   * @returns {string}
   */
  get filename(): string {
    return this._json.filename;
  }

  /**
   * Get type.
   * @returns {ReportType}
   */
  get type(): ReportType {
    return this._json.type;
  }

  /**
   * Get the json representation of this class.
   * @returns {BillingReportRequestJson}
   */
  get json(): BillingReportRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
