import { LogInspectionOverTimeSampleJson } from './__json__/log-inspection-over-time-json';

/* istanbul ignore next: autogenerated */
export class LogInspectionOverTimeSample {

  constructor(private _json: LogInspectionOverTimeSampleJson) {
  }

  /**
   * Get time.
   * @returns {number}
   */
  get time(): number {
    return this._json.time;
  }

  /**
   * Get num info.
   * @returns {number}
   */
  get numInfo(): number {
    return this._json.num_info;
  }

  /**
   * Get num low.
   * @returns {number}
   */
  get numLow(): number {
    return this._json.num_low;
  }

  /**
   * Get num medium.
   * @returns {number}
   */
  get numMedium(): number {
    return this._json.num_medium;
  }

  /**
   * Get num high.
   * @returns {number}
   */
  get numHigh(): number {
    return this._json.num_high;
  }

  /**
   * Get num critical.
   * @returns {number}
   */
  get numCritical(): number {
    return this._json.num_critical;
  }

  /**
   * Get the json representation of this class.
   * @returns {LogInspectionOverTimeSampleJson}
   */
  get json(): LogInspectionOverTimeSampleJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
