/* istanbul ignore next: autogenerated */
import { ReportWithContentJson } from './__json__';
import { ReportTypeJson } from './__json__/report-type-json';
import { ReportFormat } from './__json__/report-format';

export class ReportWithContent {

  constructor(private _json: ReportWithContentJson) {
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get entity uuid.
   * @returns {string}
   */
  get entityUuid(): string {
    return this._json.entity_uuid;
  }

  /**
   * Get report type.
   * @returns {ReportTypeJson}
   */
  get reportType(): ReportTypeJson {
    return this._json.report_type;
  }

  /**
   * Get file type.
   * @returns {ReportFormat}
   */
  get fileType(): ReportFormat {
    return this._json.file_type;
  }

  /**
   * Get created.
   * @returns {number}
   */
  get created(): number {
    return this._json.created;
  }

  /**
   * Get json content.
   * @returns {string}
   */
  get jsonContent(): string {
    return this._json.json_content;
  }

  /**
   * Get has content.
   * @returns {boolean}
   */
  get hasContent(): boolean {
    return this._json.has_content;
  }

  /**
   * Get the json representation of this class.
   * @returns {ReportWithContentJson}
   */
  get json(): ReportWithContentJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
