import { VmIntegratedBackupStatusJson } from './__json__/vm-integrated-backup-status-json';
import { IntegratedBackupStatus } from './__json__/integrated-backup-status';

/**
 * VM Integrated Backup Status.
 */
/* istanbul ignore next: autogenerated */
export class VmIntegratedBackupStatus {

  constructor(private _intBackupStatusJson: VmIntegratedBackupStatusJson) {
  }

  /**
   * Get the UUID of the VM.
   * @returns {string}
   */
  get vmUuid(): string {
    return this._intBackupStatusJson.vm_uuid;
  }

  /**
   * Get the integrated backup config status of the VM.
   * @returns {IntegratedBackupStatus}
   */
  get status(): IntegratedBackupStatus {
    return this._intBackupStatusJson.status;
  }

  /**
   * Get the json representation of this class.
   * @returns {VmIntegratedBackupStatusJson}
   */
  get json(): VmIntegratedBackupStatusJson {
    return Object.assign({}, this._intBackupStatusJson);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._intBackupStatusJson, undefined, 2);
  }
}
