import { CriteriaJson } from './__json__/criteria-json';
import { SecurityGroupOperatorType } from './__json__/security-group-operator-type';
import { SecurityGroupKeyType } from './__json__/security-group-key-type';
import { SecurityGroupCriteriaType } from './__json__/security-group-criteria-type';

/**
 * Criteria.
 */
/* istanbul ignore next: autogenerated */
export class Criteria {

  constructor(private _json: CriteriaJson) {
  }

  /**
   * Get operator.
   * @returns {SecurityGroupOperatorType}
   */
  get operator(): SecurityGroupOperatorType {
    return this._json.operator;
  }

  /**
   * Get key.
   * @returns {SecurityGroupKeyType}
   */
  get key(): SecurityGroupKeyType {
    return this._json.key;
  }

  /**
   * Get criteria.
   * @returns {SecurityGroupCriteriaType}
   */
  get criteria(): SecurityGroupCriteriaType {
    return this._json.criteria;
  }

  /**
   * Get value.
   * @returns {string}
   */
  get value(): string {
    return this._json.value;
  }

  /**
   * Get is valid.
   * @returns {boolean}
   */
  get isValid(): boolean {
    return this._json.is_valid;
  }

  /**
   * Get the json representation of this class.
   * @returns {CriteriaJson}
   */
  get json(): CriteriaJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
