import { IpSetListJson } from './__json__/ip-set-list-json';
import { IpSetJson } from './__json__/ip-set-json';

/**
 * IP Set List
 */
/* istanbul ignore next: autogenerated */
export class IpSetList {

  constructor(private _json: IpSetListJson) {
  }

  /**
   * Get data.
   * @returns {Array<IpSetJson>}
   */
  get data(): Array<IpSetJson> {
    return this._json.data;
  }

  /**
   * Get the json representation of this class.
   * @returns {IpSetListJson}
   */
  get json(): IpSetListJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
