import { SecurityGroupUpdateRequestJson } from './__json__/security-group-update-request-json';
import { SecurityGroupMemberJson } from './__json__/security-group-member-json';
import { DynamicMemberJson } from './__json__/dynamic-member-json';
import { SecurityGroupMember } from './securityGroupMember';
import { DynamicMember } from './dynamic-member';

/**
 * Security Group Update Request.
 */
/* istanbul ignore next: autogenerated */
export class SecurityGroupUpdateRequest {

  private readonly _json: SecurityGroupUpdateRequestJson;

  constructor(securityGroupUpdateRequest: SecurityGroupUpdateRequest);
  constructor(securityGroupUpdateRequestJson: SecurityGroupUpdateRequestJson);
  constructor(objectId: string, name: string, description: string, scope: string, isTemporal: boolean,
              inheritanceAllowed: boolean, includedMember: Array<SecurityGroupMemberJson>,
              excludedMember: Array<SecurityGroupMemberJson>, dynamicMember: Array<DynamicMemberJson>);
  constructor(firstParam: string | SecurityGroupUpdateRequest | SecurityGroupUpdateRequestJson, name?: string,
              description?: string, scope?: string, isTemporal?: boolean, inheritanceAllowed?: boolean,
              includedMember?: Array<SecurityGroupMemberJson>, excludedMember?: Array<SecurityGroupMemberJson>,
              dynamicMember?: Array<DynamicMemberJson>) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        object_id: firstParam,
        name: name,
        description: description,
        scope: scope,
        is_temporal: isTemporal,
        inheritance_allowed: inheritanceAllowed,
        included_member: includedMember,
        excluded_member: excludedMember,
        dynamic_member: dynamicMember
      } as SecurityGroupUpdateRequestJson;
    } else if (firstParam instanceof SecurityGroupUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as SecurityGroupUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as SecurityGroupUpdateRequestJson;
    }
  }

  /**
   * Get object id.
   * @returns {string}
   */
  get objectId(): string {
    return this._json.object_id;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get scope.
   * @returns {string}
   */
  get scope(): string {
    return this._json.scope;
  }

  /**
   * Get is temporal.
   * @returns {boolean}
   */
  get isTemporal(): boolean {
    return this._json.is_temporal;
  }

  /**
   * Get inheritance allowed.
   * @returns {boolean}
   */
  get inheritanceAllowed(): boolean {
    return this._json.inheritance_allowed;
  }

  /**
   * Get included member.
   * @returns {Array<SecurityGroupMember>}
   */
  get includedMember(): Array<SecurityGroupMember> {
    return this._json.included_member.map(it => new SecurityGroupMember(it));
  }

  /**
   * Get excluded member.
   * @returns {Array<SecurityGroupMember>}
   */
  get excludedMember(): Array<SecurityGroupMember> {
    return this._json.included_member.map(it => new SecurityGroupMember(it));
  }

  /**
   * Get dynamic member.
   * @returns {Array<DynamicMember>}
   */
  get dynamicMember(): Array<DynamicMember> {
    return this._json.dynamic_member.map(it => new DynamicMember(it));
  }

  /**
   * Get the json representation of this class.
   * @returns {SecurityGroupUpdateRequestJson}
   */
  get json(): SecurityGroupUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
