import { SecurityGroupMemberOptionPropertyJson } from './__json__/security-group-member-option-property-json';

/**
 * Security Group Member Option Property.
 */
/* istanbul ignore next: autogenerated */
export class SecurityGroupMemberOptionProperty {

  constructor(private _json: SecurityGroupMemberOptionPropertyJson) {
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get value.
   * @returns {string}
   */
  get value(): string {
    return this._json.value;
  }

  /**
   * Get the json representation of this class.
   * @returns {SecurityGroupMemberOptionPropertyJson}
   */
  get json(): SecurityGroupMemberOptionPropertyJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
