import { EdgeGatewaySyslogJson } from './__json/edge-gateway-syslog-json';

/* istanbul ignore next: autogenerated */
export class EdgeGatewaySyslogUpdateRequest {

  private readonly _json: EdgeGatewaySyslogJson;

  constructor(edgeGatewaySyslogUpdateRequest: EdgeGatewaySyslogUpdateRequest);
  constructor(edgeGatewaySyslogUpdateRequestJson: EdgeGatewaySyslogJson);
  constructor(enabled: boolean, protocol: string, serverAddresses: Array<string>);
  constructor(firstParam: boolean | EdgeGatewaySyslogUpdateRequest | EdgeGatewaySyslogJson, protocol?: string,
              serverAddresses?: Array<string>) {
    if (typeof firstParam === 'boolean') {
      // Parameters constructor
      this._json = {
        enabled: firstParam,
        protocol: protocol,
        server_addresses: serverAddresses
      } as EdgeGatewaySyslogJson;
    } else if (firstParam instanceof EdgeGatewaySyslogUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as EdgeGatewaySyslogUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as EdgeGatewaySyslogJson;
    }
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get protocol.
   * @returns {string}
   */
  get protocol(): string {
    return this._json.protocol;
  }

  /**
   * Get server addresses.
   * @returns {Array<string>}
   */
  get serverAddresses(): Array<string> {
    return this._json.server_addresses;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewaySyslogJson}
   */
  get json(): EdgeGatewaySyslogJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
