import { Entity } from '../common/entity';
import { O365JobSessionJson, O365JobSessionStats, O365JobSessionStatus } from './__json__/O365-job-session-json';
import { Iland } from '../../iland';
import { EntityType } from '../common/__json__/entity-type';
import { O365JobSessionLogItem } from './o365-job-session-log-item';
import { O365JobSessionLogItemJson } from './__json__/o365-job-session-log-item-json';

/**
 * O365 Job Session
 */
export class O365JobSession extends Entity {

  constructor(private _json: O365JobSessionJson) {
    super(_json);
  }

  /**
   * Get a O365 Job Session by UUID
   * @param uuid
   * @returns {Promise<O365JobSession>} promise that resolves with a O365 Job
   */
  static async getO365JobSession(uuid: string): Promise<O365JobSession> {
    return Iland.getHttp().get(`/o365-job-sessions/${uuid}`).then((response) => {
      const json = response.data as O365JobSessionJson;
      return new O365JobSession(json);
    });
  }

  /**
   * Get the O365 Job Session entity type
   */
  get entityType(): EntityType {
    return 'O365_JOB_SESSION';
  }

  /**
   * Gets the location id of O365 Job Session
   */
  get locationId(): string {
    return this._json.location_id;
  }

  /**
   * Gets the O365 Organization uuid of the O365 Job Session
   */
  get O365OrganizationUuid(): string {
    return this._json.o365_organization_uuid;
  }

  /**
   * Gets the O365 Job uuid of the O365 Job Session
   */
  get O365JobUuid(): string {
    return this._json.o365_job_uuid;
  }

  /**
   * Gets the creation timestamp of the O365 Job Session
   */
  get creationTime(): number {
    return this._json.creation_time;
  }

  /**
   * Gets the end time timestamp of the O365 Job Session
   */
  get endTime(): number {
    return this._json.end_time;
  }

  /**
   * Gets the progress of the O365 Job Session
   */
  get progress(): number {
    return this._json.progress;
  }

  /**
   * Gets the status of the O365 Job Session
   */
  get status(): O365JobSessionStatus {
    return this._json.status;
  }

  /**
   * Gets the statistics of the O365 Job Session
   */
  get statistics(): O365JobSessionStats {
    return this._json.statistics;
  }

  /**
   * Refresh the O365 Job Session data by retrieving it from the API again.
   * @returns {Promise<O365JobSession>}
   */
  async refresh(): Promise<O365JobSession> {
    return Iland.getHttp().get(`/o365-job-sessions/${this.uuid}`).then((response) => {
      this._json = response.data as O365JobSessionJson;
      return this;
    });
  }

  /**
   * Get the Job Session Log Items
   * @returns {Promise<Array<O365JobSessionLogItem>>}
   */
  /* istanbul ignore next: autogenerated */
  async getLogItems(): Promise<Array<O365JobSessionLogItem>> {
    return Iland.getHttp().get(`/o365-job-sessions/${this.uuid}/log-items`).then((response) => {
      const json = response.data.data as Array<O365JobSessionLogItemJson>;
      return json.map((it) => new O365JobSessionLogItem(it));
    });
  }

}
