import { O365RestoreCredentialsRequestJson } from './__json__/o365-restore-credentials-request-json';

/**
 * O365 Restore Credentials Request
 */
/* istanbul ignore next: autogenerated */
export class O365RestoreCredentialsRequest {

  constructor(private _json: O365RestoreCredentialsRequestJson) {
  }

  /**
   * Get the credential request user
   */
  get user(): string {
    return this._json.user;
  }

  /**
   * Get the credential request password
   */
  get password(): string {
    return this._json.password;
  }

  /**
   * Get the json representation of this class.
   * @returns {O365RestoreCredentialsRequestJson}
   */
  get json(): O365RestoreCredentialsRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
