import { Entity } from '../common/entity';
import {
    O365RestoreSessionJson,
    O365RestoreSessionResult, O365RestoreSessionState,
    O365RestoreSessionType
} from './__json__/o365-restore-session-json';
import { Iland } from '../../iland';
import { EntityType } from '../common/__json__/entity-type';
import { O365RestoreSessionEvent } from './o365-restore-session-event';
import { O365RestoreSessionEventJson } from './__json__/o365-restore-session-event-json';
import { O365Mailbox } from './o365-mailbox';
import { O365MailboxJson } from './__json__/o365-mailbox-json';
import { O365MailboxFolder } from './o365-mailbox-folder';
import { O365MailboxFolderJson } from './__json__/o365-mailbox-folder-json';
import { O365MailboxFolderItem } from './o365-mailbox-folder-item';
import { O365MailboxFolderItemJson } from './__json__/o365-mailbox-folder-item.json';
import { O365OneDrive } from './o365-onedrive';
import { O365OneDriveJson } from './__json__/o365-onedrive-json';
import { O365OneDriveFolder } from './o365-onedrive-folder';
import { O365OneDriveFolderJson } from './__json__/o365-onedrive-folder-json';
import { O365OneDriveDocument } from './o365-onedrive-document';
import { O365OneDriveDocumentJson } from './__json__/o365-onedrive-document-json';
import { O365SharePointSite } from './o365-sharepoint-site';
import { O365SharePointSiteJson } from './__json__/o365-sharepoint-site-json';
import { O365SharePointFolder } from './o365-sharepoint-folder';
import { O365SharePointFolderJson } from './__json__/o365-sharepoint-folder-json';
import { O365SharePointDocument } from './o365-sharepoint-document';
import { O365SharePointDocumentJson } from './__json__/o365-sharepoint-document-json';
import { O365SharePointItem } from './o365-sharepoint-item';
import { O365SharePointItemJson } from './__json__/o365-sharepoint-item-json';
import { O365SharePointLibrary } from './o365-sharepoint-library';
import { O365SharePointLibraryJson } from './__json__/o365-sharepoint-library-json';
import { O365SharePointAttachment } from './o365-sharepoint-attachment';
import { O365SharePointAttachmentJson } from './__json__/o365-sharepoint-attachment-json';
import { O365SharePointListJson } from './__json__/o365-sharepoint-list-json';
import { O365SharePointList } from './o365-sharepoint-list';
import { O365RestoreCredentialsRequest } from './o365-restore-credentials-request';
import { O365OneDriveRestoreOptionsRequest } from './o365-onedrive-restore-option-request';
import { O365SharePointRestoreOptionsRequest } from './o365-sharepoint-restore-options-request';

/**
 * O365 Restore Session
 */
export class O365RestoreSession extends Entity {

  constructor(private _json: O365RestoreSessionJson) {
    super(_json);
  }

  /**
   * Get a O365 Restore Session by UUID
   * @param uuid
   * @returns {Promise<O365RestoreSession>} promise that resolves with a O365 Restore Session
   */
  static async getO365RestoreSession(uuid: string): Promise<O365RestoreSession> {
    return Iland.getHttp().get(`/o365-restore-sessions/${uuid}`).then((response) => {
      const json = response.data as O365RestoreSessionJson;
      return new O365RestoreSession(json);
    });
  }

  /**
   * Get the O365 Restore Session entity type
   */
  get entityType(): EntityType {
    return 'O365_RESTORE_SESSION';
  }

  /**
   * Gets the location id of O365 Restore Session
   */
  get locationId(): string {
    return this._json.location_id;
  }

  /**
   * Gets the O365 Organization uuid of the O365 Restore Session
   */
  get O365OrganizationUuid(): string {
    return this._json.o365_organization_uuid;
  }

  /**
   * Get the O365 Restore Session's type
   */
  get type(): O365RestoreSessionType {
    return this._json.type;
  }

  /**
   * Get the O365 Restore Session's result
   */
  get result(): O365RestoreSessionResult {
    return this._json.result;
  }

  /**
   * Get the O365 Restore Session's state
   */
  get state(): O365RestoreSessionState {
    return this._json.state;
  }

  /**
   * Get the O365 Restore Session's creation time
   */
  get creationTime(): number {
    return this._json.creation_time;
  }

  /**
   * Get the O365 Restore Session's end time
   */
  get endTime(): number {
    return this._json.end_time;
  }

  /**
   * Get the O365 Restore Session's initiated by
   */
  get initiatedBy(): string {
    return this._json.initiated_by;
  }

  /**
   * Get the O365 Restore Session's details
   */
  get details(): string {
    return this._json.details;
  }

  /**
   * Get the O365 Restore Session's ancestors
   */
  get ancestors(): any {
    return this._json.ancestors;
  }

  /**
   * Refresh the O365 Restore Session data by retrieving it from the API again.
   * @returns {Promise<O365RestoreSession>}
   */
  /* istanbul ignore next: autogenerated */
  async refresh(): Promise<O365RestoreSession> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}`).then((response) => {
      this._json = response.data as O365RestoreSessionJson;
      return this;
    });
  }

  /**
   * Get O365 Restore Session events given the restore session uuid
   * @return {Promise<Array<O365RestoreSessionEvent>>}
   */
  /* istanbul ignore next: autogenerated */
  async getEvents(): Promise<Array<O365RestoreSessionEvent>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/events`).then((response) => {
      const json = response.data.data as Array<O365RestoreSessionEventJson>;
      return json.map((it) => new O365RestoreSessionEvent(it));
    });
  }

  /**
   * Stop O365 Restore Session
   * @return {Promise<any>}
   */
  /* istanbul ignore next: autogenerated */
  async stopRestoreSession(): Promise<any> {
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/actions/stop`);
  }

  /**
   * Get O365 Restore Session Exchange mailboxes
   *
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365Mailbox>>} the list of O365 mailboxes
   */
  /* istanbul ignore next: autogenerated */
  async getMailboxes(page?: number, pageSize?: number): Promise<Array<O365Mailbox>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/exchange-mailboxes`, {
      params: {
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365MailboxJson>;
      return json.map((it) => new O365Mailbox(it));
    });
  }

  /**
   * Get O365 Restore Session Exchange mailbox folders
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param mailboxId
   * @param folderId
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365MailboxFolder>>} the list of O365 mailbox folders
   */
  /* istanbul ignore next: autogenerated */
  async getMailboxFolders(mailboxId: string, folderId: string | null,
                          page?: number, pageSize?: number): Promise<Array<O365MailboxFolder>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/exchange-mailboxes/${mailboxId}/folders`, {
      params: {
        parentId: folderId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365MailboxFolderJson>;
      return json.map(it => new O365MailboxFolder(it));
    });
  }

  /**
   * Get O365 Restore Session Exchange mailbox folder items
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param mailboxId
   * @param folderId
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365MailboxFolderItem>>} the list of O365 mailbox folder items
   */
  /* istanbul ignore next: autogenerated */
  async getMailboxFolderItems(mailboxId: string, folderId: string | null,
                              page?: number, pageSize?: number): Promise<Array<O365MailboxFolderItem>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/exchange-mailboxes/${mailboxId}/items`, {
      params: {
        folderId: folderId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365MailboxFolderItemJson>;
      return json.map(it => new O365MailboxFolderItem(it));
    });
  }

  /**
   * Restore O365 Exchange mailbox to its original location
   * @param mailboxId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreMailboxToOriginalLocation(mailboxId: string, request: O365RestoreCredentialsRequest): Promise<any> {
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/exchange-mailboxes/${mailboxId}/actions/restore`,
        request.json);
  }

  /**
   * Restore O365 Exchange mailbox folder to its original location
   * @param mailboxId
   * @param folderId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreMailboxFolderToOriginalLocation(mailboxId: string, folderId: string,
                                               request: O365RestoreCredentialsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/exchange-mailboxes/${mailboxId}/folders/${folderId}/actions/restore`, request.json);
  }

  /**
   * Restore O365 Exchange mailbox item to its original location
   * @param mailboxId
   * @param itemId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreMailboxItemToOriginalLocation(mailboxId: string, itemId: string,
                                             request: O365RestoreCredentialsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/exchange-mailboxes/${mailboxId}/items/${itemId}/actions/restore`, request.json);
  }

  /**
   * Gets O365 Restore Session OneDrives
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365OneDrive>>} the list of O365 OneDrives
   */
  /* istanbul ignore next: autogenerated */
  async getOneDrives(page?: number, pageSize?: number): Promise<Array<O365OneDrive>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/onedrive-drives`, {
      params: {
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365OneDriveJson>;
      return json.map((it) => new O365OneDrive(it));
    });
  }

  /**
   * Gets O365 Restore Session OneDrive folders
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param oneDriveId
   * @param folderId
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365OneDriveFolder>>} the list of O365 mailbox folders
   */
  /* istanbul ignore next: autogenerated */
  async getOneDriveFolders(oneDriveId: string, folderId: string | null,
                          page?: number, pageSize?: number): Promise<Array<O365OneDriveFolder>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/onedrive-drives/${oneDriveId}/folders`, {
      params: {
        parentId: folderId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365OneDriveFolderJson>;
      return json.map(it => new O365OneDriveFolder(it));
    });
  }

  /**
   * Gets O365 Restore Session OneDrive Folder Document items
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param oneDriveId
   * @param folderId
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365OneDriveDocument>>} the list of O365 mailbox folder items
   */
  /* istanbul ignore next: autogenerated */
  async getOneDriveDocuments(oneDriveId: string, folderId: string | null,
                             page?: number, pageSize?: number): Promise<Array<O365OneDriveDocument>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/onedrive-drives/${oneDriveId}/documents`, {
      params: {
        parentId: folderId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365OneDriveDocumentJson>;
      return json.map(it => new O365OneDriveDocument(it));
    });
  }

  /**
   * Restore an O365 OneDrive
   * @param oneDriveId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreOneDrive(oneDriveId: string, request: O365OneDriveRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/onedrive-drives/${oneDriveId}/actions/restore`, request.json);
  }

  /**
   * Restore an O365 OneDrive Folder
   * @param oneDriveId
   * @param folderId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreOneDriveFolder(oneDriveId: string, folderId: string,
                              request: O365OneDriveRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/onedrive-drives/${oneDriveId}/folders/${folderId}/actions/restore`, request.json);
  }

  /**
   * Restore an O365 OneDrive Document
   * @param oneDriveId
   * @param documentId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreOneDriveDocument(oneDriveId: string, documentId: string,
                                request: O365OneDriveRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/onedrive-drives/${oneDriveId}/documents/${documentId}/actions/restore`, request.json);
  }

  /**
   * Get O365 Restore Session SharePoint sites
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param siteId - the parent folder or null for parent site
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365SharePointSite>>} the list of O365 sharepoint sites
   */
  /* istanbul ignore next: autogenerated */
  async getSharePointSites(siteId: string | null = null, page?: number,
                           pageSize?: number): Promise<Array<O365SharePointSite>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/sharepoint-sites`, {
      params: {
        parentId: siteId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365SharePointSiteJson>;
      return json.map((it) => new O365SharePointSite(it));
    });
  }

  /**
   * Restore O365 SharePoint Site
   * @param siteId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreSharePointSite(siteId: string, request: O365SharePointRestoreOptionsRequest): Promise<any> {
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/actions/restore`,
        request.json);
  }

  /**
   * Get O365 Restore Session SharePoint folders
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param siteId - the site to get folders from
   * @param parentId - the parent folder or null if the top site
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365SharePointFolder>>} the list of O365 sharepoint folders
   */
  /* istanbul ignore next: autogenerated */
  async getSharePointFolders(siteId: string, parentId: string | null, page?: number,
                             pageSize?: number): Promise<Array<O365SharePointFolder>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/folders`, {
      params: {
        parentId: parentId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365SharePointFolderJson>;
      return json.map((it) => new O365SharePointFolder(it));
    });
  }

  /**
   * Restore O365 SharePoint Folder
   * @param siteId
   * @param folderId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreSharePointFolder(siteId: string, folderId: string,
                                request: O365SharePointRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/folders/${folderId}/actions/restore`, request.json);
  }

  /**
   * Get O365 Restore Session SharePoint documents
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param siteId - the site to get documents from
   * @param parentId - the parent folder or null for top folder
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365SharePointDocument>>} the list of O365 sharepoint documents
   */
  /* istanbul ignore next: autogenerated */
  async getSharePointDocuments(siteId: string, parentId: string | null, page?: number,
                               pageSize?: number): Promise<Array<O365SharePointDocument>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/documents`, {
      params: {
        parentId: parentId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365SharePointDocumentJson>;
      return json.map((it) => new O365SharePointDocument(it));
    });
  }

  /**
   * Restore O365 SharePoint Document
   * @param siteId
   * @param documentId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreSharePointDocument(siteId: string, documentId: string,
                                  request: O365SharePointRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/documents/${documentId}/actions/restore`, request.json);
  }

  /**
   * Get O365 Restore Session SharePoint items
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param siteId - the site to get items from
   * @param parentId - the parent folder or null for top folder
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365SharePointItem>>} the list of O365 sharepoint items
   */
  /* istanbul ignore next: autogenerated */
  async getSharePointItems(siteId: string, parentId: string | null, page?: number,
                           pageSize?: number): Promise<Array<O365SharePointItem>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/items`, {
      params: {
        parentId: parentId,
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365SharePointItemJson>;
      return json.map((it) => new O365SharePointItem(it));
    });
  }

  /**
   * Restore O365 SharePoint Item
   * @param siteId
   * @param itemId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreSharePointItem(siteId: string, itemId: string,
                              request: O365SharePointRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/items/${itemId}/actions/restore`, request.json);
  }

  /**
   * Get O365 Restore Session SharePoint attachments
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param siteId - the site to get attachments from
   * @param itemId - the item parent of the attachments
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365SharePointAttachment>>} the list of O365 sharepoint attachments
   */
  /* istanbul ignore next: autogenerated */
  async getSharePointAttachments(siteId: string, itemId: string, page?: number,
                                 pageSize?: number): Promise<Array<O365SharePointAttachment>> {
    return Iland.getHttp()
        .get(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/items/${itemId}/attachments`,{
          params: {
            page: page || 0,
            pageSize: pageSize || 50
          }
        }).then((response) => {
          const json = response.data.data as Array<O365SharePointAttachmentJson>;
          return json.map((it) => new O365SharePointAttachment(it));
        });
  }
  /**
   * Get O365 Restore Session SharePoint libraries
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param siteId - the site to get items from
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365SharePointLibrary>>} the list of O365 sharepoint libraries
   */
  /* istanbul ignore next: autogenerated */
  async getSharePointLibraries(siteId: string, page?: number,
                               pageSize?: number): Promise<Array<O365SharePointLibrary>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/libraries`, {
      params: {
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365SharePointLibraryJson>;
      return json.map((it) => new O365SharePointLibrary(it));
    });
  }

  /**
   * Restore O365 SharePoint Library
   * @param siteId
   * @param libraryId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreSharePointLibrary(siteId: string, libraryId: string,
                                 request: O365SharePointRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/libraries/${libraryId}/actions/restore`, request.json);
  }

  /**
   * Get O365 Restore Session SharePoint lists
   * Proxying directly to vbo: page and pageSize are used as offset and limit respectively
   * @param siteId - the site to get items from
   * @param page
   * @param pageSize
   * @returns {Promise<Array<O365SharePointList>>} the list of O365 sharepoint lists
   */
  /* istanbul ignore next: autogenerated */
  async getSharePointLists(siteId: string, page?: number,
                           pageSize?: number): Promise<Array<O365SharePointList>> {
    return Iland.getHttp().get(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/lists`, {
      params: {
        page: page || 0,
        pageSize: pageSize || 50
      }
    }).then((response) => {
      const json = response.data.data as Array<O365SharePointListJson>;
      return json.map((it) => new O365SharePointList(it));
    });
  }

  /**
   * Restore O365 SharePoint List
   * @param siteId
   * @param listId
   * @param request
   */
  /* istanbul ignore next: autogenerated */
  async restoreSharePointList(siteId: string, listId: string,
                              request: O365SharePointRestoreOptionsRequest): Promise<any> {
    // tslint:disable-next-line:max-line-length
    return Iland.getHttp().post(`/o365-restore-sessions/${this.uuid}/sharepoint-sites/${siteId}/lists/${listId}/actions/restore`, request.json);
  }

}
