import { O365SharePointLibraryJson } from './__json__/o365-sharepoint-library-json';

/**
 * O365 SharePoint Library
 */
/* istanbul ignore next: autogenerated */
export class O365SharePointLibrary {

  constructor(private _json: O365SharePointLibraryJson) {
  }

  /**
   * Gets the id of the SharePoint Library
   */
  get id(): string {
    return this._json.id;
  }

  /**
   * Gets the name of the SharePoint Library
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Gets the description of the SharePoint Library
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Gets the url of the SharePoint Library
   */
  get url(): string {
    return this._json.url;
  }

  /**
   * Gets the creation time of the SharePoint Library
   */
  get creationTime(): number {
    return this._json.creation_time;
  }

  /**
   * Get the json representation of this class.
   * @returns {O365SharePointLibraryJson}
   */
  get json(): O365SharePointLibraryJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
