import { O365SharePointFolderJson, O365SharePointFolderType } from './__json__/o365-sharepoint-folder-json';

/**
 * O365 SharePoint Folder
 */
/* istanbul ignore next: autogenerated */
export class O365SharePointFolder {

  constructor(private _json: O365SharePointFolderJson) {
  }

  /**
   * Gets the id of the SharePoint Folder
   */
  get id(): string {
    return this._json.id;
  }

  /**
   * Gets the name of the SharePoint Folder
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Gets the created by of the SharePoint Folder
   */
  get createdBy(): string {
    return this._json.created_by;
  }

  /**
   * Gets the creation time of the SharePoint Folder
   */
  get creationTime(): number {
    return this._json.creation_time;
  }

  /**
   * Gets the modified by of the SharePoint Folder
   */
  get modifiedBy(): string {
    return this._json.modified_by;
  }

  /**
   * Gets the modification time of the SharePoint Folder
   */
  get modificationTime(): number {
    return this._json.modification_time;
  }

  /**
   * Gets the type of SharePoint Folder
   */
  get type(): O365SharePointFolderType {
    return this._json.type;
  }

  /**
   * Get the json representation of this class.
   * @returns {O365SharePointFolderJson}
   */
  get json(): O365SharePointFolderJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
