import { O365GroupJson } from './__json__/o365-group-json';

/**
 * O365 Group entity
 */
/* istanbul ignore next: autogenerated */
export class O365Group {

  constructor(private _json: O365GroupJson) {
  }

  /**
   * Get the O365 Group display name
   */
  get displayName(): string {
    return this._json.display_name;
  }

  /**
   * Get the O365 Group organization's name
   */
  get organizationName(): string {
    return this._json.organization_name;
  }

  /**
   * Get the O365 VBO Organization iland platform UUID
   */
  get organizationUuid(): string {
    return this._json.organization_uuid;
  }

  /**
   * Get the O365 Group type
   */
  get type(): string {
    return this._json.type;
  }

  /**
   * Get the O365 Group name
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get the O365 Group native id
   */
  get nativeId(): string {
    return this._json.native_id;
  }

  /**
   * Get whether the Office 365 Group is backed up
   */
  get isBackedUp(): boolean {
    return this._json.is_backed_up;
  }

  /**
   * Get whether the Office 365 Group has been deleted from the O365 organization
   */
  get isDeletedFromOrg(): boolean {
    return this._json.is_deleted_from_org;
  }

  /**
   * Get the json representation of this class.
   * @returns {O365GroupJson}
   */
  get json(): O365GroupJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
