import { HasSnapshotJson } from './__json__/has-snapshot-json';

/**
 * HasSnapshot. Whether a VM or vApp has a snapshot.
 */
/* istanbul ignore next: autogenerated */
export class HasSnapshot {

  constructor(private _json: HasSnapshotJson) {
  }

  /**
   * Get has snapshot.
   * @returns {boolean}
   */
  get hasSnapshot(): boolean {
    return this._json.has_snapshot;
  }

  /**
   * Get the json representation of this class.
   * @returns {HasSnapshotJson}
   */
  get json(): HasSnapshotJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
