export enum SAMLNameIdPolicyFormatEnum {
  PERSISTENT = 'PERSISTENT',
  EMAIL_ADDRESS = 'EMAIL_ADDRESS',
  KERBEROS = 'KERBEROS',
  X509_SUBJECT_NAME = 'X509_SUBJECT_NAME',
  WINDOWS_DOMAIN_QUALIFIED_NAME = 'WINDOWS_DOMAIN_QUALIFIED_NAME',
  UNSPECIFIED = 'UNSPECIFIED'
}

export type SAMLNameIdPolicyFormat = keyof typeof SAMLNameIdPolicyFormatEnum;
