import { BatchFailoverParamsRequestJson } from './__json__/batch-failover-params-request-json';
import { FailoverParamsRequestJson } from './__json__/failover-params-request-json';

/* istanbul ignore next: autogenerated */
export class BatchFailoverParamsRequest {

  private readonly _json: BatchFailoverParamsRequestJson;

  constructor(batchFailoverParamsRequest: BatchFailoverParamsRequest);
  constructor(batchFailoverParamsRequestJson: BatchFailoverParamsRequestJson);
  constructor(firstParam: BatchFailoverParamsRequest | BatchFailoverParamsRequestJson) {
    if (firstParam instanceof BatchFailoverParamsRequest) {
      // Copy constructor
      this._json = (firstParam as BatchFailoverParamsRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as BatchFailoverParamsRequestJson;
    }
  }

  /**
   * Get batch params.
   * @returns {{ [key: string]: FailoverParamsRequestJson }}
   */
  get batchParams(): { [key: string]: FailoverParamsRequestJson } {
    return this._json.batch_params;
  }

  /**
   * Get the json representation of this class.
   * @returns {BatchFailoverParamsRequestJson}
   */
  get json(): BatchFailoverParamsRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
