"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Nessus History.
 */
/* istanbul ignore next: autogenerated */
var NessusHistory = (function () {
    function NessusHistory(_json) {
        this._json = _json;
    }
    Object.defineProperty(NessusHistory.prototype, "historyId", {
        /**
         * Get history id.
         * @returns {number}
         */
        get: function () {
            return this._json.history_id;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHistory.prototype, "uuid", {
        /**
         * Get uuid.
         * @returns {string}
         */
        get: function () {
            return this._json.uuid;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHistory.prototype, "ownerId", {
        /**
         * Get owner id.
         * @returns {number}
         */
        get: function () {
            return this._json.owner_id;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHistory.prototype, "status", {
        /**
         * Get status.
         * @returns {string}
         */
        get: function () {
            return this._json.status;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHistory.prototype, "creationDate", {
        /**
         * Get creation date.
         * @returns {number}
         */
        get: function () {
            return this._json.creation_date;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHistory.prototype, "lastModificationDate", {
        /**
         * Get last modification date.
         * @returns {number}
         */
        get: function () {
            return this._json.last_modification_date;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHistory.prototype, "json", {
        /**
         * Get the json representation of this class.
         * @returns {NessusHistoryJson}
         */
        get: function () {
            return Object.assign({}, this._json);
        },
        enumerable: true,
        configurable: true
    });
    /**
     * Get the string representation of this class.
     * @returns {string}
     */
    NessusHistory.prototype.toString = function () {
        return JSON.stringify(this._json, undefined, 2);
    };
    return NessusHistory;
}());
exports.NessusHistory = NessusHistory;
