import { NessusScanDetailsJson } from './__json__/nessus-scan-details-json';
import { NessusRemediations } from './nessus-remediations';
import { NessusScanInfo } from './nessus-scan-info';
import { NessusVulnerability } from './nessus-vulnerability';
import { NessusHost } from './nessus-host';
import { NessusHistory } from './nessus-history';
import { NessusNote } from './nessus-note';

/**
 * Nessus Scan Details.
 */
/* istanbul ignore next: autogenerated */
export class NessusScanDetails {

  constructor(private _json: NessusScanDetailsJson) {
  }

  /**
   * Get info.
   * @returns {NessusScanInfo}
   */
  get info(): NessusScanInfo {
    return new NessusScanInfo(this._json.info);
  }

  /**
   * Get remediations.
   * @returns {NessusRemediations}
   */
  get remediations(): NessusRemediations {
    return new NessusRemediations(this._json.remediations);
  }

  /**
   * Get vulnerabilities.
   * @returns {Array<NessusVulnerability>}
   */
  get vulnerabilities(): Array<NessusVulnerability> {
    return this._json.vulnerabilities.map(it => new NessusVulnerability(it));
  }

  /**
   * Get hosts.
   * @returns {Array<NessusHost>}
   */
  get hosts(): Array<NessusHost> {
    return this._json.hosts.map(it => new NessusHost(it));
  }

  /**
   * Get comp hosts.
   * @returns {Array<NessusHost>}
   */
  get compHosts(): Array<NessusHost> {
    return this._json.comp_hosts.map(it => new NessusHost(it));
  }

  /**
   * Get history.
   * @returns {Array<NessusHistory>}
   */
  get history(): Array<NessusHistory> {
    return this._json.history.map(it => new NessusHistory(it));
  }

  /**
   * Get notes.
   * @returns {Array<NessusNote>}
   */
  get notes(): Array<NessusNote> {
    return this._json.notes.map(it => new NessusNote(it));
  }

  /**
   * Get compliance.
   * @returns {Array<NessusVulnerability>}
   */
  get compliance(): Array<NessusVulnerability> {
    return this._json.compliance.map(it => new NessusVulnerability(it));
  }

  /**
   * Get vulnerabilities by host.
   * @returns {{ [key: number]: Array<NessusVulnerability> }}
   */
  get vulnsByHost(): { [key: number]: Array<NessusVulnerability> } {
    const mapped: { [key: number]: Array<NessusVulnerability> } = {};
    for (const key in this._json.vulns_by_host) {
      mapped[key] = this._json.vulns_by_host[key].map(it => new NessusVulnerability(it));
    }
    return mapped;
  }

  /**
   * Get the json representation of this class.
   * @returns {NessusScanDetailsJson}
   */
  get json(): NessusScanDetailsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
