"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 *  Nessus Launch result.
 */
/* istanbul ignore next: autogenerated */
var NessusLaunch = (function () {
    function NessusLaunch(_json) {
        this._json = _json;
    }
    Object.defineProperty(NessusLaunch.prototype, "scanUuid", {
        /**
         * Get scan uuid.
         * @returns {string}
         */
        get: function () {
            return this._json.scan_uuid;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusLaunch.prototype, "error", {
        /**
         * Get error.
         * @returns {string}
         */
        get: function () {
            return this._json.error;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusLaunch.prototype, "json", {
        /**
         * Get the json representation of this class.
         * @returns {NessusLaunchJson}
         */
        get: function () {
            return Object.assign({}, this._json);
        },
        enumerable: true,
        configurable: true
    });
    /**
     * Get the string representation of this class.
     * @returns {string}
     */
    NessusLaunch.prototype.toString = function () {
        return JSON.stringify(this._json, undefined, 2);
    };
    return NessusLaunch;
}());
exports.NessusLaunch = NessusLaunch;
