"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Nessus Note.
 */
/* istanbul ignore next: autogenerated */
var NessusNote = (function () {
    function NessusNote(_json) {
        this._json = _json;
    }
    Object.defineProperty(NessusNote.prototype, "title", {
        /**
         * Get title.
         * @returns {string}
         */
        get: function () {
            return this._json.title;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusNote.prototype, "message", {
        /**
         * Get message.
         * @returns {string}
         */
        get: function () {
            return this._json.message;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusNote.prototype, "severity", {
        /**
         * Get severity.
         * @returns {number}
         */
        get: function () {
            return this._json.severity;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusNote.prototype, "json", {
        /**
         * Get the json representation of this class.
         * @returns {NessusNoteJson}
         */
        get: function () {
            return Object.assign({}, this._json);
        },
        enumerable: true,
        configurable: true
    });
    /**
     * Get the string representation of this class.
     * @returns {string}
     */
    NessusNote.prototype.toString = function () {
        return JSON.stringify(this._json, undefined, 2);
    };
    return NessusNote;
}());
exports.NessusNote = NessusNote;
