"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Nessus Host.
 */
/* istanbul ignore next: autogenerated */
var NessusHost = (function () {
    function NessusHost(_json) {
        this._json = _json;
    }
    Object.defineProperty(NessusHost.prototype, "hostId", {
        /**
         * Get host id.
         * @returns {number}
         */
        get: function () {
            return this._json.host_id;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "hostIndex", {
        /**
         * Get host index.
         * @returns {string}
         */
        get: function () {
            return this._json.host_index;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "hostName", {
        /**
         * Get host name.
         * @returns {number}
         */
        get: function () {
            return this._json.host_name;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "progress", {
        /**
         * Get progress.
         * @returns {string}
         */
        get: function () {
            return this._json.progress;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "critical", {
        /**
         * Get critical.
         * @returns {number}
         */
        get: function () {
            return this._json.critical;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "high", {
        /**
         * Get high.
         * @returns {number}
         */
        get: function () {
            return this._json.high;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "medium", {
        /**
         * Get medium.
         * @returns {number}
         */
        get: function () {
            return this._json.medium;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "low", {
        /**
         * Get low.
         * @returns {number}
         */
        get: function () {
            return this._json.low;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "info", {
        /**
         * Get info.
         * @returns {number}
         */
        get: function () {
            return this._json.info;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "totalChecksConsidered", {
        /**
         * Get total checks considered.
         * @returns {number}
         */
        get: function () {
            return this._json.total_checks_considered;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "numChecksConsidered", {
        /**
         * Get num checks considered.
         * @returns {number}
         */
        get: function () {
            return this._json.num_checks_considered;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "scanProgressTotal", {
        /**
         * Get scan progress total.
         * @returns {number}
         */
        get: function () {
            return this._json.scan_progress_total;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "scanProgressCurrent", {
        /**
         * Get scan progress current.
         * @returns {number}
         */
        get: function () {
            return this._json.scan_progress_current;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "score", {
        /**
         * Get score.
         * @returns {number}
         */
        get: function () {
            return this._json.score;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(NessusHost.prototype, "json", {
        /**
         * Get the json representation of this class.
         * @returns {NessusHostJson}
         */
        get: function () {
            return Object.assign({}, this._json);
        },
        enumerable: true,
        configurable: true
    });
    /**
     * Get the string representation of this class.
     * @returns {string}
     */
    NessusHost.prototype.toString = function () {
        return JSON.stringify(this._json, undefined, 2);
    };
    return NessusHost;
}());
exports.NessusHost = NessusHost;
