import { NessusScanInfoJson } from './__json__/nessus-scan-info-json';

/**
 * Nessus Scan Info.
 */
/* istanbul ignore next: autogenerated */
export class NessusScanInfo {

  constructor(private _json: NessusScanInfoJson) {
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get edit allowed.
   * @returns {boolean}
   */
  get editAllowed(): boolean {
    return this._json.edit_allowed;
  }

  /**
   * Get status.
   * @returns {string}
   */
  get status(): string {
    return this._json.status;
  }

  /**
   * Get policy.
   * @returns {string}
   */
  get policy(): string {
    return this._json.policy;
  }

  /**
   * Get pci can upload.
   * @returns {boolean}
   */
  get pciCanUpload(): boolean {
    return this._json.pci_can_upload;
  }

  /**
   * Get has audit trail.
   * @returns {boolean}
   */
  get hasAuditTrail(): boolean {
    return this._json.has_audit_trail;
  }

  /**
   * Get scan start.
   * @returns {number}
   */
  get scanStart(): number {
    return this._json.scan_start;
  }

  /**
   * Get folder id.
   * @returns {number}
   */
  get folderId(): number {
    return this._json.folder_id;
  }

  /**
   * Get targets.
   * @returns {string}
   */
  get targets(): string {
    return this._json.targets;
  }

  /**
   * Get timestamp.
   * @returns {number}
   */
  get timestamp(): number {
    return this._json.timestamp;
  }

  /**
   * Get object id.
   * @returns {number}
   */
  get objectId(): number {
    return this._json.object_id;
  }

  /**
   * Get scanner name.
   * @returns {string}
   */
  get scannerName(): string {
    return this._json.scanner_name;
  }

  /**
   * Get haskb.
   * @returns {boolean}
   */
  get haskb(): boolean {
    return this._json.haskb;
  }

  /**
   * Get host count.
   * @returns {number}
   */
  get hostCount(): number {
    return this._json.host_count;
  }

  /**
   * Get scan end.
   * @returns {number}
   */
  get scanEnd(): number {
    return this._json.scan_end;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get user permissions.
   * @returns {number}
   */
  get userPermissions(): number {
    return this._json.user_permissions;
  }

  /**
   * Get control.
   * @returns {boolean}
   */
  get control(): boolean {
    return this._json.control;
  }

  /**
   * Get the json representation of this class.
   * @returns {NessusScanInfoJson}
   */
  get json(): NessusScanInfoJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
