import { VmAffinityRuleUpdateRequestJson } from './__json__/vm-affinity-rule-update-request-json';
import { VmAffinityRuleOperation } from './__json__/vm-affinity-rule-operation-type';
import { AffinityRuleType } from './__json__/affinity-rule-type';

/**
 * VM Affinity Rule Update Request.
 */
/* istanbul ignore next: autogenerated */
export class VmAffinityRuleUpdateRequest {

  private readonly _json: VmAffinityRuleUpdateRequestJson;

  constructor(vmAffinityRuleUpdateRequest: VmAffinityRuleUpdateRequest);
  constructor(vmAffinityRuleUpdateRequestJson: VmAffinityRuleUpdateRequestJson);
  constructor(vms: Array<string>, name: string, enabled: boolean, type: AffinityRuleType, uuid: string,
              operation: VmAffinityRuleOperation, key: number);
  constructor(firstParam: Array<string> | VmAffinityRuleUpdateRequest | VmAffinityRuleUpdateRequestJson, name?: string,
              enabled?: boolean, type?: AffinityRuleType, uuid?: string, operation?: VmAffinityRuleOperation,
              key?: number) {
    if (firstParam instanceof Array) {
      // Parameters constructor
      this._json = {
        vms: firstParam,
        name: name,
        enabled: enabled,
        type: type,
        uuid: uuid,
        operation: operation,
        key: key
      } as VmAffinityRuleUpdateRequestJson;
    } else if (firstParam instanceof VmAffinityRuleUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as VmAffinityRuleUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VmAffinityRuleUpdateRequestJson;
    }
  }

  /**
   * Get vms.
   * @returns {Array<string>}
   */
  get vms(): Array<string> {
    return this._json.vms;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get type.
   * @returns {AffinityRuleType}
   */
  get type(): AffinityRuleType {
    return this._json.type;
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get operation.
   * @returns {VmAffinityRuleOperation}
   */
  get operation(): VmAffinityRuleOperation {
    return this._json.operation;
  }

  /**
   * Get key.
   * @returns {number}
   */
  get key(): number {
    return this._json.key;
  }

  /**
   * Get the json representation of this class.
   * @returns {VmAffinityRuleUpdateRequestJson}
   */
  get json(): VmAffinityRuleUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
