/**
 * Enumeration of possible Vpg Sub Status types.
 */
export type VpgSubStatus = 'NONE' |
  'INITIAL_SYNC' |
  'CREATING' |
  'VOLUME_INITIAL_SYNC' |
  'SYNC' |
  'RECOVERY_POSSIBLE' |
  'DELTA_SYNC' |
  'NEEDS_CONFIGURATION' |
  'ERROR' |
  'EMPTY_PROTECTION_GROUP' |
  'DISCONNECTED_FROM_PEER_NO_RECOVERY_POINTS' |
  'FULL_SYNC' |
  'VOLUME_DELTA_SYNC' |
  'VOLUME_FULL_SYNC' |
  'FAILING_OVER_COMMITTING' |
  'FAILING_OVER_BEFORE_COMMIT' |
  'FAILING_OVER_ROLLING_BACK' |
  'PROMOTING' |
  'MOVING_COMMITTING' |
  'MOVING_BEFORE_COMMIT' |
  'MOVING_ROLLING_BACK' |
  'DELETING' |
  'PENDING_REMOVE' |
  'BITMAP_SYNC' |
  'DISCONNECTED_FROM_PEER' |
  'REPLICATION_PAUSED_USER_INITIATED' |
  'REPLICATION_PAUSED_SYSTEM_INITIATED' |
  'RECOVERY_STORAGE_PROFILE_ERROR' |
  'BACKUP' |
  'ROLLING_BACK' |
  'RECOVERY_STORAGE_ERROR' |
  'JOURNAL_STORAGE_ERROR' |
  'VM_NOT_PROTECTED_ERROR';
