import { VappTemplateFromVappCreateRequestJson } from './__json__/vapp-template-from-vapp-create-request-json';

/* istanbul ignore next: autogenerated */
export class VappTemplateFromVappCreateRequest {

  private readonly _json: VappTemplateFromVappCreateRequestJson;

  constructor(vappTemplateFromVappCreateRequest: VappTemplateFromVappCreateRequest);
  constructor(vappTemplateFromVappCreateRequestJson: VappTemplateFromVappCreateRequestJson);
  constructor(vappUuid: string, name: string, description: string);
  constructor(firstParam: string | VappTemplateFromVappCreateRequest | VappTemplateFromVappCreateRequestJson,
              name?: string, description?: string) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        vapp_uuid: firstParam,
        name: name,
        description: description
      } as VappTemplateFromVappCreateRequestJson;
    } else if (firstParam instanceof VappTemplateFromVappCreateRequest) {
      // Copy constructor
      this._json = (firstParam as VappTemplateFromVappCreateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VappTemplateFromVappCreateRequestJson;
    }
  }

  /**
   * Get vapp uuid.
   * @returns {string}
   */
  get vappUuid(): string {
    return this._json.vapp_uuid;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get the json representation of this class.
   * @returns {VappTemplateFromVappCreateRequestJson}
   */
  get json(): VappTemplateFromVappCreateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
