import { SecurityTagVmJson } from './__json__/security-tag-vm-json';

/**
 * Virtual Machine assigned to the Security Tag.
 */
/* istanbul ignore next: autogenerated */
export class SecurityTagVm {

  constructor(private _json: SecurityTagVmJson) {
  }

  /**
   * Get object id.
   * @returns {string}
   */
  get objectId(): string {
    return this._json.object_id;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get scope.
   * @returns {string}
   */
  get scope(): string {
    return this._json.scope;
  }

  /**
   * Get the json representation of this class.
   * @returns {SecurityTagVmJson}
   */
  get json(): SecurityTagVmJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
