import { SecurityTagObjectPagingParamsJson } from './__json__/security-tag-object-paging-params-json';

/**
 * Security Tag Object Paging Params.
 */
/* istanbul ignore next: autogenerated */
export class SecurityTagObjectPagingParams {

  constructor(private _json: SecurityTagObjectPagingParamsJson) {
  }

  /**
   * Get page.
   * @returns {number}
   */
  get page(): number {
    return this._json.page;
  }

  /**
   * Get page size.
   * @returns {number}
   */
  get pageSize(): number {
    return this._json.page_size;
  }

  /**
   * Get filter.
   * @returns {string | undefined}
   */
  get filter(): string | undefined {
    return this._json.filter || undefined;
  }

  /**
   * Get the json representation of this class.
   * @returns {SecurityTagObjectPagingParamsJson}
   */
  get json(): SecurityTagObjectPagingParamsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
