import { SecurityTagObjectJson } from './__json__/security-tag-object-json';
import { SecurityTagObjectProperty } from './security-tag-object-property';

/**
 * Security Tag Object.
 */
/* istanbul ignore next: autogenerated */
export class SecurityTagObject {

  constructor(private _json: SecurityTagObjectJson) {
  }

  /**
   * Get type.
   * @returns {string}
   */
  get type(): string {
    return this._json.type;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get properties.
   * @returns {Array<SecurityTagObjectProperty>}
   */
  get properties(): Array<SecurityTagObjectProperty> {
    return this._json.properties.map(it => new SecurityTagObjectProperty(it));
  }

  /**
   * Get the json representation of this class.
   * @returns {SecurityTagObjectJson}
   */
  get json(): SecurityTagObjectJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
