import { SecurityTagCreateRequestJson } from './__json__/security-tag-create-request-json';

/**
 * Security Tag Create Request.
 */
/* istanbul ignore next: autogenerated */
export class SecurityTagCreateRequest {

  private readonly _json: SecurityTagCreateRequestJson;

  constructor(securityTagCreateRequest: SecurityTagCreateRequest);
  constructor(securityTagCreateRequestJson: SecurityTagCreateRequestJson);
  constructor(name: string, description: string, assignedVmIds: Array<string>);
  constructor(firstParam: string | SecurityTagCreateRequest | SecurityTagCreateRequestJson, description?: string,
              assignedVmIds?: Array<string>) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        name: firstParam,
        description: description,
        assigned_vm_ids: assignedVmIds
      } as SecurityTagCreateRequestJson;
    } else if (firstParam instanceof SecurityTagCreateRequest) {
      // Copy constructor
      this._json = (firstParam as SecurityTagCreateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as SecurityTagCreateRequestJson;
    }
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get assigned vm ids.
   * @returns {Array<string>}
   */
  get assignedVmIds(): Array<string> {
    return this._json.assigned_vm_ids;
  }

  /**
   * Get the json representation of this class.
   * @returns {SecurityTagCreateRequestJson}
   */
  get json(): SecurityTagCreateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
