import { IpRangeRequestJson } from '../common/ip-range/__json__';
import { VappNetworkDHCPServiceUpdateRequestJson } from './__json__/vapp-network-dhcp-service-update-request-json';
import { IpRangeRequest } from '../common/ip-range/ip-range-request';

/* istanbul ignore next: autogenerated */
export class VappNetworkDHCPServiceUpdateRequest {

  private readonly _json: VappNetworkDHCPServiceUpdateRequestJson;

  constructor(vappNetworkDHCPServiceUpdateRequest: VappNetworkDHCPServiceUpdateRequest);
  constructor(vappNetworkDHCPServiceUpdateRequestJson: VappNetworkDHCPServiceUpdateRequestJson);
  constructor(enabled: boolean, ipRange: IpRangeRequestJson, defaultLeaseTime: number, maxLeaseTime: number);
  constructor(firstParam: boolean | VappNetworkDHCPServiceUpdateRequest | VappNetworkDHCPServiceUpdateRequestJson,
              ipRange?: IpRangeRequestJson, defaultLeaseTime?: number, maxLeaseTime?: number) {
    if (typeof firstParam === 'boolean') {
      // Parameters constructor
      this._json = {
        enabled: firstParam,
        ip_range: ipRange,
        default_lease_time: defaultLeaseTime,
        max_lease_time: maxLeaseTime
      } as VappNetworkDHCPServiceUpdateRequestJson;
    } else if (firstParam instanceof VappNetworkDHCPServiceUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as VappNetworkDHCPServiceUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VappNetworkDHCPServiceUpdateRequestJson;
    }
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get ip range.
   * @returns {IpRangeRequest}
   */
  get ipRange(): IpRangeRequest {
    return new IpRangeRequest(this._json.ip_range);
  }

  /**
   * Get default lease time.
   * @returns {number}
   */
  get defaultLeaseTime(): number {
    return this._json.default_lease_time;
  }

  /**
   * Get max lease time.
   * @returns {number}
   */
  get maxLeaseTime(): number {
    return this._json.max_lease_time;
  }

  /**
   * Get the json representation of this class.
   * @returns {VappNetworkDHCPServiceUpdateRequestJson}
   */
  get json(): VappNetworkDHCPServiceUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
