/* istanbul ignore next: autogenerated */
export interface BaBackupDirectoryJson {
  uuid: string;
  name: string;
  size_mb: number;
  modified_at: number;
  repository_name: string;
  backup_server_name: string;
  recycled: boolean;
}
