import { StorageProfileBillJson } from './__json__/storage-profile-bill-json';

/**
 * Storage Profile Bill.
 */
/* istanbul ignore next: autogenerated */
export class StorageProfileBill {

  constructor(private _json: StorageProfileBillJson) {
  }

  /**
   * Get storage profile uuid.
   * @returns {string}
   */
  get storageProfileUuid(): string {
    return this._json.storage_profile_uuid;
  }

  /**
   * Get total usage.
   * @returns {number}
   */
  get totalUsage(): number {
    return this._json.total_usage;
  }

  /**
   * Get total cost.
   * @returns {number}
   */
  get totalCost(): number {
    return this._json.total_cost;
  }

  /**
   * Get res usage.
   * @returns {number}
   */
  get resUsage(): number {
    return this._json.res_usage;
  }

  /**
   * Get res cost.
   * @returns {number}
   */
  get resCost(): number {
    return this._json.res_cost;
  }

  /**
   * Get burst usage.
   * @returns {number}
   */
  get burstUsage(): number {
    return this._json.burst_usage;
  }

  /**
   * Get burst cost.
   * @returns {number}
   */
  get burstCost(): number {
    return this._json.burst_cost;
  }

  /**
   * Get vm usage.
   * @returns {number}
   */
  get vmUsage(): number {
    return this._json.vm_usage;
  }

  /**
   * Get catalog usage.
   * @returns {number}
   */
  get catalogUsage(): number {
    return this._json.catalog_usage;
  }

  /**
   * Get Zerto journal storage usage.
   * @returns {number} 0 if not a Zerto environ
   */
  get zertoJournalStorageUsage(): number {
    return this._json.zerto_journal_storage_usage;
  }

  /**
   * Get Zerto replicated storage usage.
   * @returns {number} 0 if not a Zerto environ
   */
  get zertoReplicatedStorageUsage(): number {
    return this._json.zerto_replicated_storage_usage;
  }

  /**
   * Get the json representation of this class.
   * @returns {StorageProfileBillJson}
   */
  get json(): StorageProfileBillJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
