import { Vm } from '../vm/vm';
import { AffinityRuleType } from './__json__/affinity-rule-type';
import { VmAffinityRuleJson } from './__json__/vm-affinity-rule-json';

/**
 * VM  Affinity Rule.
 */
/* istanbul ignore next: autogenerated */
export class VmAffinityRule {

  constructor(private _json: VmAffinityRuleJson) {
  }

  /**
   * Get vm uuids.
   * @returns {Array<string>}
   */
  get vmUuids(): Array<string> {
    return this._json.vm_uuids;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get type.
   * @returns {AffinityRuleType}
   */
  get type(): AffinityRuleType {
    return this._json.type;
  }

  /**
   * Get isMandatory.
   * @returns {boolean}
   */
  get isMandatory(): boolean {
    return this._json.is_mandatory;
  }

  /**
   * Get Vm list
   * @returns {Promise<Array<Vm>>}
   */
  async getVms(): Promise<Array<Vm>> {
    return Promise.all(this._json.vm_uuids.map(async it => Vm.getVm(it)));
  }

  /**
   * Get the json representation of this class.
   * @returns {VmAffinityRuleJson}
   */
  get json(): VmAffinityRuleJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
