export type EntityDomainType =
  'COMPANY' |
  'ILAND_CLOUD_PRODUCT' |
  'ILAND_BACKUP_PRODUCT' |
  'ILAND_CLOUD_LOCATION' |
  'ILAND_CLOUD_ORGANIZATION' |
  'ILAND_CLOUD_VPG' |
  'ILAND_CLOUD_CATALOG' |
  'ILAND_CLOUD_MEDIA' |
  'ILAND_CLOUD_VAPP_TEMPLATE' |
  'ILAND_CLOUD_VDC' |
  'ILAND_CLOUD_EDGE' |
  'ILAND_CLOUD_INTERNAL_NETWORK' |
  'ILAND_CLOUD_VAPP' |
  'ILAND_CLOUD_VAPP_NETWORK' |
  'ILAND_CLOUD_VM' |
  'ILAND_BACKUP_LOCATION' |
  'ILAND_BACKUP_TENANT';
