export type IamEntityType =
  'COMPANY' |
  'IAAS_PRODUCT' |
  'IAAS_LOCATION' |
  'IAAS_ORGANIZATION' |
  'IAAS_VPG' |
  'IAAS_VCC_FAILOVER_PLAN' |
  'IAAS_CATALOG' |
  'IAAS_MEDIA' |
  'IAAS_VAPP_TEMPLATE' |
  'IAAS_VDC' |
  'IAAS_EDGE' |
  'IAAS_INTERNAL_NETWORK' |
  'IAAS_VAPP' |
  'IAAS_VAPP_NETWORK' |
  'IAAS_VM' |
  'VCC_BACKUP_PRODUCT' |
  'VCC_BACKUP_LOCATION' |
  'VCC_BACKUP_TENANT' |
  'OBJECT_STORAGE_PRODUCT' |
  'OBJECT_STORAGE_LOCATION';
