import { CommitPolicy } from './__json__/vpg-failover-commit-policy-type';
import { ShutdownPolicy } from './__json__/vpg-failover-shutdown-policy-type';
import { VpgFailoverCreateRequestJson } from './__json__/vpg-failover-create-request-json';

/**
 * Vpg Failover Create Request
 */
/* istanbul ignore next: autogenerated */
export class VpgFailoverCreateRequest {

  private readonly _json: VpgFailoverCreateRequestJson;

  constructor(failoverCreateRequest: VpgFailoverCreateRequest);
  constructor(VpgFailoverCreateRequestJson: VpgFailoverCreateRequestJson);
  constructor(checkpointIdentifier: string, commitPolicy: CommitPolicy, shutdownPolicy: ShutdownPolicy,
              timeToWaitBeforeShutdownInSec: number, commitValue: number);
  constructor(firstParam: string | VpgFailoverCreateRequest | VpgFailoverCreateRequestJson, commitPolicy?: CommitPolicy,
              shutdownPolicy?: ShutdownPolicy, timeToWaitBeforeShutdownInSec?: number, commitValue?: number) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        checkpoint_identifier: firstParam,
        commit_policy: commitPolicy,
        shutdown_policy: shutdownPolicy,
        time_to_wait_before_shutdown_in_sec: timeToWaitBeforeShutdownInSec,
        commit_value: commitValue
      } as VpgFailoverCreateRequestJson;
    } else if (firstParam instanceof VpgFailoverCreateRequest) {
      // Copy constructor
      this._json = (firstParam as VpgFailoverCreateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VpgFailoverCreateRequestJson;
    }
  }

  /**
   * Get checkpoint identifier.
   * @returns {string}
   */
  get checkpointIdentifier(): string {
    return this._json.checkpoint_identifier;
  }

  /**
   * Get commit policy.
   * @returns {CommitPolicy}
   */
  get commitPolicy(): CommitPolicy {
    return this._json.commit_policy;
  }

  /**
   * Get shutdown policy.
   * @returns {ShutdownPolicy}
   */
  get shutdownPolicy(): ShutdownPolicy {
    return this._json.shutdown_policy;
  }

  /**
   * Get time to wait before shutdown in sec.
   * @returns {number}
   */
  get timeToWaitBeforeShutdownInSec(): number {
    return this._json.time_to_wait_before_shutdown_in_sec;
  }

  /**
   * Get commit value.
   * @returns {number}
   */
  get commitValue(): number {
    return this._json.commit_value;
  }

  /**
   * Get the json representation of this class.
   * @returns {VpgFailoverCreateRequestJson}
   */
  get json(): VpgFailoverCreateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
