import { BaBackupFilterParamsJson } from '../../__json__/ba-backup-filter-params-json';
import { BaBackupFileJson } from './ba-backup-file-json';

/* istanbul ignore next: autogenerated */
export interface BaBackupFileListJson {
  current_page_parameters: BaBackupFilterParamsJson;
  next_page_parameters: BaBackupFilterParamsJson;
  total_records: number;
  last_page: boolean;
  data: Array<BaBackupFileJson>;
}
