import { CompanyTwoFactorAuthSettingsJson } from './__json__/company-two-factor-auth-settings-json';

/**
 * Company Two Factor Auth Settings
 * - To apply 2FA to all users, set 'allUsers' to true and set 'rolesUuids' to null or empty.
 * - To apply 2FA to specific roles, set 'allUsers' to false and fill 'roleUuids' with role uuids.
 */
/* istanbul ignore next: autogenerated */
export class CompanyTwoFactorAuthSettings {
  constructor(private _json: CompanyTwoFactorAuthSettingsJson) {
  }

  /**
   * Get all users.
   * @returns {boolean}
   */
  get allUsers(): boolean {
    return this._json.all_users;
  }

  /**
   * Get role uuids.
   * @returns {Array<String>}
   */
  get roleUuids(): Array<String> {
    return this._json.role_uuids || [];
  }

  /**
   * Get the json representation of this class.
   * @returns {CompanyTwoFactorAuthSettingsJson}
   */
  get json(): CompanyTwoFactorAuthSettingsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
