import { O365BackupRepositoryJson } from './__json__/o365-backup-repository-json';

/**
 * O365 Backup Repository
 */
/* istanbul ignore next: autogenerated */
export class O365BackupRepository {

  constructor(private _json: O365BackupRepositoryJson) {
  }

  /**
   * Get name of Backup Repo
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get description of Backup Repo
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get id of Backup Repo
   */
  get id(): string {
    return this._json.id;
  }

  /**
   * Get the json representation of this class.
   * @returns {O365BackupRepositoryJson}
   */
  get json(): O365BackupRepositoryJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
