import { O365BillJson } from './__json__/o365-bill-json';
import { CurrencyCode } from '../common/billing/__json__/currency-code-type';

/**
 * O365 Bill
 */
/* istanbul ignore next: autogenerated */
export class O365Bill {

  constructor(private _json: O365BillJson) {
  }

  /**
   * Get cost per license of O365 bill
   */
  get costPerLicense(): number {
    return this._json.cost_per_license;
  }

  /**
   * Get currency code of O365 bill
   */
  get currencyCode(): CurrencyCode {
    return this._json.currency_code.currency_code;
  }

  /**
   * Get full month contract cost of O365 bill
   */
  get fullMonthContractCost(): number {
    return this._json.full_month_contract_cost;
  }

  /**
   * Get month of O365 bill
   */
  get month(): number {
    return this._json.month;
  }

  /**
   * Get number of licenses of O365 bill
   */
  get numberOfLicenses(): number {
    return this._json.number_of_licenses;
  }

  /**
   * Get total of O365 bill
   */
  get total(): number {
    return this._json.total;
  }

  /**
   * Get year of O365 bill
   */
  get year(): number {
    return this._json.year;
  }

  /**
   * Get the json representation of this class
   * @return {O365BillJson}
   */
  get json(): O365BillJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
