import { SalesforceSubscriptionJson } from './__json__/sales-force-subscription-json';

/**
 * SalesforceSubscription class
 */
/* istanbul ignore next: autogenerated */
export class SalesforceSubscription {

  constructor(private _json: SalesforceSubscriptionJson) {
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get contract.
   * @returns {string}
   */
  get contract(): string {
    return this._json.contract;
  }

  /**
   * Get currency code.
   * @returns {string}
   */
  get currencyCode(): string {
    return this._json.currency_code;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get contract number.
   * @returns {string}
   */
  get contractNumber(): string {
    return this._json.contract_number;
  }

  /**
   * Get console total monthly cost.
   * @returns {number}
   */
  get consoleTotalMonthlyCost(): number {
    return this._json.console_total_monthly_cost;
  }

  /**
   * Get product id.
   * @returns {string}
   */
  get productId(): string {
    return this._json.product_id;
  }

  /**
   * Get console cost per unit.
   * @returns {number}
   */
  get consoleCostPerUnit(): number {
    return this._json.console_cost_per_unit;
  }

  /**
   * Get quantity.
   * @returns {number}
   */
  get quantity(): number {
    return this._json.quantity;
  }

  /**
   * Get account id.
   * @returns {string}
   */
  get accountId(): string {
    return this._json.account_id;
  }

  /**
   * Get product name.
   * @returns {string}
   */
  get productName(): string {
    return this._json.product_name;
  }

  /**
   * Get deployment date.
   * @returns {Date | null}
   */
  get deploymentDate(): Date | null {
    return this._json.deployment_date ? new Date(this._json.deployment_date) : null;
  }

  /**
   * Get product.
   * @returns {string}
   */
  get product(): string {
    return this._json.product;
  }

  /**
   * Get product code.
   * @returns {string}
   */
  get productCode(): string {
    return this._json.product_code;
  }

  /**
   * Get cancellation date.
   * @returns {Date | null}
   */
  get cancellationDate(): Date | null {
    return this._json.cancellation_date ? new Date(this._json.cancellation_date) : null;
  }

  /**
   * Get the json representation of this class.
   * @returns {SalesforceSubscriptionJson}
   */
  get json(): SalesforceSubscriptionJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
