import { BackupPolicyListJson } from './__json__/backup-policy-list-json';
import { BackupPolicy } from './backup-policy';

/**
 * Backup Policy List.
 */
/* istanbul ignore next: autogenerated */
export class BackupPolicyList {

  constructor(private _json: BackupPolicyListJson) {
  }

  /**
   * Get data.
   * @returns {Array<BackupPolicy>}
   */
  get data(): Array<BackupPolicy> {
    return this._json.data?.map(it => new BackupPolicy(it));
  }

  /**
   * Get the json representation of this class.
   * @returns {BackupPolicyListJson}
   */
  get json(): BackupPolicyListJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
