import { RecoveryGroupDescriptorJson } from './__json__/recovery-group-descriptor-json';
import { RecoveryGroupDescriptor } from './recovery-group-descriptor';
import { DisasterRecoveryRunbookUpdateRequestJson } from './__json__/disaster-recovery-runbook-update-request-json';

/**
 * Disaster recovery runbook update request.
 */
/* istanbul ignore next: autogenerated */
export class DisasterRecoveryRunbookUpdateRequest {

  private readonly _json: DisasterRecoveryRunbookUpdateRequestJson;

  constructor(disasterRecoveryRunbookUpdateRequest: DisasterRecoveryRunbookUpdateRequest);
  constructor(disasterRecoveryRunbookUpdateRequestJson: DisasterRecoveryRunbookUpdateRequestJson);
  constructor(name: string, description: string, recoveryGroups: Array<RecoveryGroupDescriptorJson>);
  constructor(firstParam: string | DisasterRecoveryRunbookUpdateRequest | DisasterRecoveryRunbookUpdateRequestJson,
              description?: string, recoveryGroups?: Array<RecoveryGroupDescriptorJson>) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        name: firstParam,
        description: description,
        recovery_groups: recoveryGroups
      } as DisasterRecoveryRunbookUpdateRequestJson;
    } else if (firstParam instanceof DisasterRecoveryRunbookUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as DisasterRecoveryRunbookUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as DisasterRecoveryRunbookUpdateRequestJson;
    }
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get recovery groups.
   * @returns {Array<RecoveryGroupDescriptor>}
   */
  get recoveryGroups(): Array<RecoveryGroupDescriptor> {
    return this._json.recovery_groups.map(rGroup => {
      return new RecoveryGroupDescriptor(rGroup);
    });
  }

  /**
   * Get the json representation of this class.
   * @returns {DisasterRecoveryRunbookUpdateRequestJson}
   */
  get json(): DisasterRecoveryRunbookUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
