import {
  DisasterRecoveryRunbookFinalizeExecutionRequestJson
} from
    './__json__/disaster-recovery-runbook-finalize-execution-request-json';
import { CommitPolicy } from '../../vpg/vpg-failover/__json__/vpg-failover-commit-policy-type';

/**
 * Disaster recovery runbook finalize execution request.
 */
/* istanbul ignore next: autogenerated */
export class DisasterRecoveryRunbookFinalizeExecutionRequest {

  private readonly _json: DisasterRecoveryRunbookFinalizeExecutionRequestJson;

  constructor(disasterRecoveryRunbookFinalizeExecutionRequest: DisasterRecoveryRunbookFinalizeExecutionRequest);
  constructor(disasterRecoveryRunbookFinalizeExecutionRequestJson: DisasterRecoveryRunbookFinalizeExecutionRequestJson);
  constructor(parentRunbookTaskUuid: string, finalizeRecoveryParams: { [key: string]: CommitPolicy });
  constructor(firstParam: string | DisasterRecoveryRunbookFinalizeExecutionRequest |
    DisasterRecoveryRunbookFinalizeExecutionRequestJson, finalizeRecoveryParams?: { [key: string]: CommitPolicy }) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        parent_runbook_task_uuid: firstParam,
        finalize_recovery_params: finalizeRecoveryParams
      } as DisasterRecoveryRunbookFinalizeExecutionRequestJson;
    } else if (firstParam instanceof DisasterRecoveryRunbookFinalizeExecutionRequest) {
      // Copy constructor
      this._json = (firstParam as DisasterRecoveryRunbookFinalizeExecutionRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as DisasterRecoveryRunbookFinalizeExecutionRequestJson;
    }
  }

  /**
   * Get parent runbook task uuid.
   * @returns {string}
   */
  get parentRunbookTaskUuid(): string {
    return this._json.parent_runbook_task_uuid;
  }

  /**
   * Get finalize recovery params.
   * @returns {{ [key: string]: CommitPolicy }}
   */
  get finalizeRecoveryParams(): { [key: string]: CommitPolicy } {
    return this._json.finalize_recovery_params;
  }

  /**
   * Get the json representation of this class.
   * @returns {DisasterRecoveryRunbookFinalizeExecutionRequestJson}
   */
  get json(): DisasterRecoveryRunbookFinalizeExecutionRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
