"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jpeg_image_1 = require("../../common/jpeg-image");
/**
 * Vm bootup log
 */
/* istanbul ignore next: autogenerated */
var VmBootupLog = (function () {
    function VmBootupLog(_json) {
        this._json = _json;
    }
    Object.defineProperty(VmBootupLog.prototype, "vmUuid", {
        /**
         * Get vm uuid.
         * @returns {string}
         */
        get: function () {
            return this._json.vm_uuid;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(VmBootupLog.prototype, "vmName", {
        /**
         * Get vm name.
         * @returns {string}
         */
        get: function () {
            return this._json.vm_name;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(VmBootupLog.prototype, "screenshot", {
        /**
         * Get screenshot.
         * @returns {JpegImage}
         */
        get: function () {
            var screenShotBuff = new Buffer(this._json.screenshot);
            return new jpeg_image_1.JpegImage(screenShotBuff);
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(VmBootupLog.prototype, "timestamp", {
        /**
         * Get timestamp.
         * @returns {number}
         */
        get: function () {
            return this._json.timestamp;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(VmBootupLog.prototype, "ipAddress", {
        /**
         * Get ip address.
         * @returns {string}
         */
        get: function () {
            return this._json.ip_address;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(VmBootupLog.prototype, "errorLog", {
        /**
         * Get error log.
         * @returns {string}
         */
        get: function () {
            return this._json.error_log;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(VmBootupLog.prototype, "json", {
        /**
         * Get the json representation of this class.
         * @returns {VmBootupLogJson}
         */
        get: function () {
            return Object.assign({}, this._json);
        },
        enumerable: true,
        configurable: true
    });
    /**
     * Get the string representation of this class.
     * @returns {string}
     */
    VmBootupLog.prototype.toString = function () {
        return JSON.stringify(this._json, undefined, 2);
    };
    return VmBootupLog;
}());
exports.VmBootupLog = VmBootupLog;
