import { EdgeGatewayDhcpStaticBindingJson } from './__json__/edge-gateway-dhcp-static-binding-json';
import { EdgeGatewayDhcpOptions } from './edge-gateway-dhcp-options';

/**
 * DHCP Static Binding.
 */
/* istanbul ignore next: autogenerated */
export class EdgeGatewayDhcpStaticBinding {

  constructor(private _json: EdgeGatewayDhcpStaticBindingJson) {
  }

  /**
   * Get auto configure dns.
   * @returns {boolean}
   */
  get autoConfigureDNS(): boolean {
    return this._json.auto_configure_dns;
  }

  /**
   * Get binding id.
   * @returns {string}
   */
  get bindingId(): string {
    return this._json.binding_id;
  }

  /**
   * Get vm id.
   * @returns {string}
   */
  get vmId(): string {
    return this._json.vm_id;
  }

  /**
   * Get vnic id.
   * @returns {number}
   */
  get vnicId(): number {
    return this._json.vnic_id;
  }

  /**
   * Get hostname.
   * @returns {string}
   */
  get hostname(): string {
    return this._json.hostname;
  }

  /**
   * Get ip address.
   * @returns {string}
   */
  get ipAddress(): string {
    return this._json.ip_address;
  }

  /**
   * Get default gateway.
   * @returns {string}
   */
  get defaultGateway(): string {
    return this._json.default_gateway;
  }

  /**
   * Get domain name.
   * @returns {string}
   */
  get domainName(): string {
    return this._json.domain_name;
  }

  /**
   * Get primary name server.
   * @returns {string}
   */
  get primaryNameServer(): string {
    return this._json.primary_name_server;
  }

  /**
   * Get secondary name server.
   * @returns {string}
   */
  get secondaryNameServer(): string {
    return this._json.secondary_name_server;
  }

  /**
   * Get lease time.
   * @returns {string}
   */
  get leaseTime(): string {
    return this._json.lease_time;
  }

  /**
   * Get mac address.
   * @returns {string}
   */
  get macAddress(): string {
    return this._json.mac_address;
  }

  /**
   * Get subnet mask.
   * @returns {string}
   */
  get subnetMask(): string {
    return this._json.subnet_mask;
  }

  /**
   * Get dhcp options.
   * @returns {EdgeGatewayDhcpOptions}
   */
  get dhcpOptions(): EdgeGatewayDhcpOptions {
    return new EdgeGatewayDhcpOptions(this._json.dhcp_options);
  }

  /**
   * Get next server.
   * @returns {string}
   */
  get nextServer(): string {
    return this._json.next_server;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayDhcpStaticBindingJson}
   */
  get json(): EdgeGatewayDhcpStaticBindingJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
