import {
  EdgeGatewayDhcpRelayTypeOptionPagingParamsJson
} from './__json__/edge-gateway-dhcp-relay-type-option-paging-params-json';

/* istanbul ignore next: autogenerated */
export class EdgeGatewayDhcpRelayTypeOptionPagingParams {

  constructor(private _json: EdgeGatewayDhcpRelayTypeOptionPagingParamsJson) {}

  /**
   * Get page.
   * @returns {number}
   */
  get page(): number {
    return this._json.page;
  }

  /**
   * Get page size.
   * @returns {number}
   */
  get pageSize(): number {
    return this._json.page_size;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayDhcpRelayTypeOptionPagingParamsJson}
   */
  get json(): EdgeGatewayDhcpRelayTypeOptionPagingParamsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
