import { EdgeGatewayDhcpJson } from './__json__/edge-gateway-dhcp-json';
import { EdgeGatewayDhcpIpPool } from './edge-gateway-dhcp-ip-pool';
import { EdgeGatewayDhcpLogging } from './edge-gateway-dhcp-logging';
import { EdgeGatewayDhcpRelay } from './edge-gateway-dhcp-relay';
import { EdgeGatewayDhcpStaticBinding } from './edge-gateway-dhcp-static-binding';

/* istanbul ignore next: autogenerated */
export class EdgeGatewayDhcp {

  constructor(private _json: EdgeGatewayDhcpJson) {}

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get static bindings.
   * @returns {Array<EdgeGatewayDhcpStaticBinding>}
   */
  get staticBindings(): Array<EdgeGatewayDhcpStaticBinding> {
    return this._json.static_bindings.map(it => new EdgeGatewayDhcpStaticBinding(it));
  }

  /**
   * Get ip pools.
   * @returns {Array<EdgeGatewayDhcpIpPool>}
   */
  get ipPools(): Array<EdgeGatewayDhcpIpPool> {
    return this._json.ip_pools.map(it => new EdgeGatewayDhcpIpPool(it));
  }

  /**
   * Get logging.
   * @returns {EdgeGatewayDhcpLogging}
   */
  get logging(): EdgeGatewayDhcpLogging {
    return new EdgeGatewayDhcpLogging(this._json.logging);
  }

  /**
   * Get relay.
   * @returns {EdgeGatewayDhcpRelay}
   */
  get relay(): EdgeGatewayDhcpRelay {
    return new EdgeGatewayDhcpRelay(this._json.relay);
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayDhcpJson}
   */
  get json(): EdgeGatewayDhcpJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
