import { OIDCIdentityProviderConfigRequestJson } from './__json__/oidc-identity-provider-config-request-json';
import { OIDCClientAuthType } from './__json__/oidc-client-auth-type';
import { OIDCPromptType } from './__json__/oidc-prompt-type';

/* istanbul ignore next: autogenerated */
export class OIDCIdentityProviderConfigRequest {

  private readonly _json: OIDCIdentityProviderConfigRequestJson;

  constructor(OIDCIdentityProviderConfigRequest: OIDCIdentityProviderConfigRequest);
  constructor(OIDCIdentityProviderConfigRequestJson: OIDCIdentityProviderConfigRequestJson);
  constructor(firstParam: OIDCIdentityProviderConfigRequest | OIDCIdentityProviderConfigRequestJson) {
    if (firstParam instanceof OIDCIdentityProviderConfigRequest) {
      // Copy constructor
      this._json = (firstParam as OIDCIdentityProviderConfigRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as OIDCIdentityProviderConfigRequestJson;
    }
  }

  /**
   * Get enforce SSO.
   * @returns {boolean}
   */
  get enforceSSO(): boolean {
    return this._json.enforce_sso;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get authorization url.
   * @returns {string}
   */
  get authorizationUrl(): string {
    return this._json.authorization_url;
  }

  /**
   * Get logout URL.
   * @returns {string | undefined}
   */
  get logoutUrl(): string | undefined {
    return this._json.logout_url;
  }

  /**
   * Get login hint.
   * @returns {boolean | undefined}
   */
  get loginHint(): boolean | undefined {
    return this._json.login_hint;
  }

  /**
   * Get ui locales.
   * @returns {boolean | undefined}
   */
  get uiLocales(): boolean | undefined {
    return this._json.ui_locales;
  }

  /**
   * Get token url.
   * @returns {string}
   */
  get tokenUrl(): string {
    return this._json.token_url;
  }

  /**
   * Get user info url.
   * @returns {string | undefined}
   */
  get userInfoUrl(): string | undefined {
    return this._json.user_info_url;
  }

  /**
   * Get backchannel supported.
   * @returns {boolean | undefined}
   */
  get backchannelSupported(): boolean | undefined {
    return this._json.backchannel_supported;
  }

  /**
   * Get disable user info.
   * @returns {boolean | undefined}
   */
  get disableUserInfo(): boolean | undefined {
    return this._json.disable_user_info;
  }

  /**
   * Get client id.
   * @returns {string}
   */
  get clientId(): string {
    return this._json.client_id;
  }

  /**
   * Get client secret.
   * @returns {string}
   */
  get clientSecret(): string {
    return this._json.client_secret;
  }

  /**
   * Get client auth.
   * @returns {OIDCClientAuthType}
   */
  get clientAuth(): OIDCClientAuthType {
    return this._json.client_auth;
  }

  /**
   * Get issuer.
   * @returns {string | undefined}
   */
  get issuer(): string | undefined {
    return this._json.issuer;
  }

  /**
   * Get default scope.
   * @returns {string | undefined}
   */
  get defaultScope(): string | undefined {
    return this._json.default_scope;
  }

  /**
   * Get prompt.
   * @returns {OIDCPromptType | undefined}
   */
  get prompt(): OIDCPromptType | undefined {
    return this._json.prompt;
  }

  /**
   * Get accepts prompt none forward from client.
   * @returns {boolean | undefined}
   */
  get acceptsPromptNoneForwardFromClient(): boolean | undefined {
    return this._json.accepts_prompt_none_forward_from_client;
  }

  /**
   * Get validate signature.
   * @returns {boolean | undefined}
   */
  get validateSignature(): boolean | undefined {
    return this._json.validate_signature;
  }

  /**
   * Get use jwks url.
   * @returns {boolean | undefined}
   */
  get useJwksUrl(): boolean | undefined {
    return this._json.use_jwks_url;
  }

  /**
   * Get jwks url.
   * @returns {string | undefined}
   */
  get jwksUrl(): string | undefined {
    return this._json.jwks_url;
  }

  /**
   * Get public key signature verifier key.
   * @returns {string | undefined}
   */
  get publicKeySignatureVerifierKey(): string | undefined {
    return this._json.public_key_signature_verifier_key;
  }

  /**
   * Get public key signature verifier key id.
   * @returns {string | undefined}
   */
  get publicKeySignatureVerifierKeyId(): string | undefined {
    return this._json.public_key_signature_verifier_key_id;
  }

  /**
   * Get allowed clock skew.
   * @returns {number | undefined}
   */
  get allowedClockSkew(): number | undefined {
    return this._json.allowed_clock_skew;
  }

  /**
   * Get forward parameters.
   * @returns {string | undefined}
   */
  get forwardParameters(): string | undefined {
    return this._json.forward_parameters;
  }

  /**
   * Get the json representation of this class.
   * @returns {OIDCIdentityProviderConfigRequestJson}
   */
  get json(): OIDCIdentityProviderConfigRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
