import { SAMLIdentityProviderConfigRequestJson } from './__json__/saml-identity-provider-config-request-json';
import { SAMLNameIdPolicyFormat } from './__json__/saml-name-id-policy-format';
import { SAMLPrincipalType } from './__json__/saml-principal-type';
import { SAMLSignatureAlgorithm } from './__json__/saml-signature-algorithm';
import { SAMLSignatureKeyName } from './__json__/saml-signature-key-name';

/* istanbul ignore next: autogenerated */
export class SAMLIdentityProviderConfigRequest {

  private readonly _json: SAMLIdentityProviderConfigRequestJson;

  constructor(immutableSAMLIdentityProviderConfigRequest: SAMLIdentityProviderConfigRequest);
  constructor(immutableSAMLIdentityProviderConfigRequestJson: SAMLIdentityProviderConfigRequestJson);
  constructor(firstParam: SAMLIdentityProviderConfigRequest | SAMLIdentityProviderConfigRequestJson) {
    // Parameters constructor
    if (firstParam instanceof SAMLIdentityProviderConfigRequest) {
      // Copy constructor
      this._json = (firstParam as SAMLIdentityProviderConfigRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as SAMLIdentityProviderConfigRequestJson;
    }
  }

  /**
   * Get enforce sso.
   * @returns {boolean}
   */
  get enforceSso(): boolean {
    return this._json.enforce_sso;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get single sign on service url.
   * @returns {string}
   */
  get singleSignOnServiceUrl(): string {
    return this._json.single_sign_on_service_url;
  }

  /**
   * Get single logout service URL.
   * @returns {string | undefined}
   */
  get singleLogoutServiceUrl(): string | undefined {
    return this._json.single_logout_service_url;
  }

  /**
   * Get name id policy format.
   * @returns {SAMLNameIdPolicyFormat | undefined}
   */
  get nameIsPolicyFormat(): SAMLNameIdPolicyFormat | undefined {
    return this._json.name_id_policy_format;
  }

  /**
   * Get principal type.
   * @returns {SAMLPrincipalType | undefined}
   */
  get principalType(): SAMLPrincipalType | undefined {
    return this._json.principal_type;
  }

  /**
   * Get principal attribute.
   * @returns {string | undefined}
   */
  get principalAttribute(): string | undefined {
    return this._json.principal_attribute;
  }

  /**
   * Get signature algorithm.
   * @returns {SAMLSignatureAlgorithm | undefined}
   */
  get signatureAlgorithm(): SAMLSignatureAlgorithm | undefined {
    return this._json.signature_algorithm;
  }

  /**
   * Get saml xml key name tranformer.
   * @returns {SAMLSignatureKeyName | undefined}
   */
  get samlXmlKeyNameTranformer(): SAMLSignatureKeyName | undefined {
    return this._json.saml_xml_key_name_tranformer;
  }

  /**
   * Get backchannel supported.
   * @returns {boolean | undefined}
   */
  get backchannelSupported(): boolean | undefined {
    return this._json.backchannel_supported;
  }

  /**
   * Get post binding response.
   * @returns {boolean | undefined}
   */
  get postBindingResponse(): boolean | undefined {
    return this._json.post_binding_response;
  }

  /**
   * Get post binding authn request.
   * @returns {boolean | undefined}
   */
  get postBindingAuthnRequest(): boolean | undefined {
    return this._json.post_binding_authn_request;
  }

  /**
   * Get post binding logout.
   * @returns {boolean | undefined}
   */
  get postBindingLogout(): boolean | undefined {
    return this._json.post_binding_logout;
  }

  /**
   * Get want authn requests signed.
   * @returns {boolean | undefined}
   */
  get wantAuthnRequestsSigned(): boolean | undefined {
    return this._json.want_authn_requests_signed;
  }

  /**
   * Get want assertions signed.
   * @returns {boolean | undefined}
   */
  get wantAssertionsSigned(): boolean | undefined {
    return this._json.want_assertions_signed;
  }

  /**
   * Get signing certificate.
   * @returns {string | undefined}
   */
  get signingCertificate(): string | undefined {
    return this._json.signing_certificate;
  }

  /**
   * Get want assertions encrypted.
   * @returns {boolean | undefined}
   */
  get wantAssertionsEncrypted(): boolean | undefined {
    return this._json.want_assertions_encrypted;
  }

  /**
   * Get force authn.
   * @returns {boolean | undefined}
   */
  get forceAuthn(): boolean | undefined {
    return this._json.force_authn;
  }

  /**
   * Get validate signature.
   * @returns {boolean | undefined}
   */
  get validateSignature(): boolean | undefined {
    return this._json.validate_signature;
  }

  /**
   * Get allowed clock skew.
   * @returns {string | undefined}
   */
  get allowedClockSkew(): string | undefined {
    return this._json.allowed_clock_skew;
  }

  /**
   * Get the json representation of this class.
   * @returns {SAMLIdentityProviderConfigRequestJson}
   */
  get json(): SAMLIdentityProviderConfigRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
