import { IdentityProvider } from './identity-provider';
import { SAMLIdentityProviderJson } from './__json__/saml-identity-provider-json';
import { IdentityProviderType } from './__json__/identity-provider-type';

/* istanbul ignore next: autogenerated */
export class SAMLIdentityProvider extends IdentityProvider {

  constructor(private _json: SAMLIdentityProviderJson) {
    super(_json);
  }

  /**
   * Get enforce sso.
   * @returns {boolean}
   */
  get enforceSso(): boolean {
    return this._json.enforce_sso;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get single sign on service url.
   * @returns {string}
   */
  get singleSignOnServiceUrl(): string {
    return this._json.single_sign_on_service_url;
  }

  /**
   * Get single logout service URL.
   * @returns {string}
   */
  get singleLogoutServiceUrl(): string {
    return this._json.single_logout_service_url;
  }

  /**
   * Get name id policy format.
   * @returns {string}
   */
  get nameIdPolicyFormat(): string {
    return this._json.name_id_policy_format;
  }

  /**
   * Get principal type.
   * @returns {string}
   */
  get principalType(): string {
    return this._json.principal_type;
  }

  /**
   * Get principal attribute.
   * @returns {string}
   */
  get principalAttribute(): string {
    return this._json.principal_attribute;
  }

  /**
   * Get signature algorithm.
   * @returns {string}
   */
  get signatureAlgorithm(): string {
    return this._json.signature_algorithm;
  }

  /**
   * Get saml xml key name tranformer.
   * @returns {string}
   */
  get samlXmlKeyNameTranformer(): string {
    return this._json.saml_xml_key_name_tranformer;
  }

  /**
   * Get backchannel supported.
   * @returns {boolean}
   */
  get backchannelSupported(): boolean {
    return this._json.backchannel_supported;
  }

  /**
   * Get post binding response.
   * @returns {boolean}
   */
  get postBindingResponse(): boolean {
    return this._json.post_binding_response;
  }

  /**
   * Get post binding authn request.
   * @returns {boolean}
   */
  get postBindingAuthnRequest(): boolean {
    return this._json.post_binding_authn_request;
  }

  /**
   * Get post binding logout.
   * @returns {boolean}
   */
  get postBindingLogout(): boolean {
    return this._json.post_binding_logout;
  }

  /**
   * Get want authn requests signed.
   * @returns {boolean}
   */
  get wantAuthnRequestsSigned(): boolean {
    return this._json.want_authn_requests_signed;
  }

  /**
   * Get want assertions signed.
   * @returns {boolean}
   */
  get wantAssertionsSigned(): boolean {
    return this._json.want_assertions_signed;
  }

  /**
   * Get want assertions encrypted.
   * @returns {boolean}
   */
  get wantAssertionsEncrypted(): boolean {
    return this._json.want_assertions_encrypted;
  }

  /**
   * Get signing certificate.
   * @returns {string}
   */
  get signingCertificate(): string {
    return this._json.signing_certificate;
  }

  /**
   * Get force authn.
   * @returns {boolean}
   */
  get forceAuthn(): boolean {
    return this._json.force_authn;
  }

  /**
   * Get validate signature.
   * @returns {boolean}
   */
  get validateSignature(): boolean {
    return this._json.validate_signature;
  }

  /**
   * Get allowed clock skew.
   * @returns {string}
   */
  get allowedClockSkew(): string {
    return this._json.allowed_clock_skew;
  }

  /**
   * Get type.
   * @returns {IdentityProviderType}
   */
  get type(): IdentityProviderType {
    return this._json.type;
  }

  /**
   * Get the json representation of this class.
   * @returns {SAMLIdentityProviderJson}
   */
  get json(): SAMLIdentityProviderJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
