/**
 * Enumeration of possible event types.
 */
export type EventType =

    // ORG

    'ORG_CREATE' |

    'ORG_MODIFY' |

    'ORG_ANTIMALWARE_REPORT_GENERATE' |

    'ORG_BILLING_REPORT_GENERATE' |

    'ORG_CONTINUITY_PROTECTION_REPORT_GENERATE' |

    'ORG_DR_ADMIN_REPORT_GENERATE' |

    'ORG_DPI_EVENT_REPORT_GENERATE' |

    'ORG_ECS_EVENT_HISTORY_REPORT_GENERATE' |

    'ORG_FAILOVER_TEST_REPORT_GENERATE' |

    'ORG_FIREWALL_EVENT_REPORT_GENERATE' |

    'ORG_HIPAA_REPORT_GENERATE' |

    'ORG_INTEGRITY_EVENT_REPORT_GENERATE' |

    'ORG_LOG_INSPECTION_REPORT_GENERATE' |

    'ORG_LOGIN_EVENT_HISTORY_REPORT_GENERATE' |

    'ORG_SUPPORT_REQUEST_REPORT_GENERATE' |

    'ORG_VM_ENCRYPTION_REPORT_GENERATE' |

    'ORG_VULNERABILITY_REPORT_GENERATE' |

    'ORG_WEB_REPUTATION_REPORT_GENERATE' |

    'ORG_DR_RUNBOOK_REPORT_GENERATE' |

    'ORG_VM_INVENTORY_REPORT_GENERATE' |

    'ORG_BILL_CALCULATED' |

    'ORG_DELETE_DNS_ZONE' |

    'ORG_PUSH_DNS_ZONE' |

    'ORG_UPDATE_DNS_RECORD' |

    'ORG_VULNERABILITY_SCAN_LAUNCH' |

    'ORG_VULNERABILITY_SCAN_PAUSE' |

    'ORG_VULNERABILITY_SCAN_STOP' |

    'ORG_VULNERABILITY_SCAN_RESUME' |

    // EDGE

    'EDGE_CREATE' |

    'EDGE_MODIFY' |

    'EDGE_FIREWALL_MODIFIED' |

    // VM

    'VM_CREATE' |

    'VM_DELETE' |

    'VM_MODIFY_REQUEST' |

    'VM_DEPLOY_REQUEST' |

    'VM_UNDEPLOY' |

    'VM_CONSOLIDATE_REQUEST' |

    'VM_RELOCATE_REQUEST' |

    'VM_IP_ADDRESS_CHANGED' |

    'VM_RESTORE_BACKUP_END' |

    'VM_BILL_CALCULATED' |

    'VM_ANTIMALWARE_EVENT' |

    'VM_LOG_INSPECTION_EVENT' |

    'VM_INTEGRITY_EVENT' |

    'VM_UPDATE_VMWARE_TOOLS_UPGRADE_POLICY' |

    'VM_UPDATE_BOOT_OPTIONS' |

    'VM_DRS_RULES_UPDATE' |

    'VM_DRS_RULES_DELETE' |

    // VAPP

    'VAPP_CREATE' |

    'VAPP_DELETE' |

    'VAPP_DEPLOY' |

    'VAPP_UPLOAD_TIMEOUT' |

    'VAPP_IMPORT_REQUEST' |

    'VAPP_CREATE_REQUEST' |

    'VAPP_DEPLOY_REQUEST' |

    'VAPP_LEASE_EXPIRATION_CHANGED' |

    'VAPP_BILL_CALCULATED' |

    'VAPP_DOWNLOAD' |

    // VDC

    'VDC_VM_INVENTORY_REPORT_GENERATE' |

    'VDC_CREATE_REQUEST' |

    'VDC_CREATE' |

    'VDC_MODIFY' |

    'VDC_FAST_PROVISIONING_MODIFY' |

    'VDC_THIN_PROVISIONING_MODIFY' |

    'VDC_BILL_CALCULATED' |

    // PROVIDER VDC

    'PROVIDER_VDC_CREATE' |

    'PROVIDER_VDC_CREATE_REQUEST' |

    'PROVIDER_VDC_DELETE' |

    'PROVIDER_VDC_DELETE_REQUEST' |

    'PROVIDER_VDC_MODIFY' |

    // VAPP NETWORK

    'VAPP_NETWORK_CREATE' |

    'VAPP_NETWORK_MODIFY' |

    'VAPP_NETWORK_UNDEPLOY' |

    // ORG VDC NETWORK

    'ORG_VDC_NETWORK_CREATE' |

    'ORG_VDC_NETWORK_MODIFY' |

    'ORG_VDC_NETWORK_UNDEPLOY' |

    'ORG_VDC_NETWORK_UPGRADE' |

    // EXTERNAL NETWORK

    'EXTERNAL_NETWORK_CREATE' |

    'EXTERNAL_NETWORK_MODIFY' |

    'EXTERNAL_NETWORK_UNDEPLOY' |

    // MEDIA

    'MEDIA_CREATE' |

    'MEDIA_MODIFY' |

    'MEDIA_CREATE_REQUEST' |

    'MEDIA_MODIFY_REQUEST' |

    'MEDIA_UPLOAD_TIMEOUT' |

    // VAPP TEMPLATE

    'VAPP_TEMPLATE_CREATE' |

    'VAPP_TEMPLATE_MODIFY' |

    'VAPP_TEMPLATE_CREATE_REQUEST' |

    'VAPP_TEMPLATE_IMPORT_REQUEST' |

    'VAPP_TEMPLATE_MODIFY_REQUEST' |

    'VAPP_TEMPLATE_DELETE_REQUEST' |

    'VAPP_TEMPLATE_ENABLE_DOWNLOAD' |

    'VAPP_TEMPLATE_DOWNLOAD' |

    // CATALOG

    'CATALOG_CREATE' |

    'CATALOG_MODIFY' |

    // USER

    'VCD_USER_SESSION_LOGIN' |

    'VCD_USER_IMPORT' |

    'VCD_USER_MODIFY' |

    'VCD_USER_UNLOCK' |

    'VCD_USER_CREATE' |

    'VCD_USER_ENABLE' |

    // USER / KEYCLOAK BASED

    'USER_LOGIN' |

    'USER_REFRESH_TOKEN' |

    'USER_UPDATE_TOTP' |

    'USER_SEND_RESET_PASSWORD' |

    'USER_IMPERSONATE' |

    // TASK

    'TASK_CREATE' |

    'TASK_ABORT' |

    'TASK_FAIL' |

    // STORAGE PROFILE

    'STORAGE_PROFILE_CREATE' |

    'STORAGE_PROFILE_MODIFY' |

    'STORAGE_PROFILE_ADD' |

    'STORAGE_PROFILE_REMOVE' |

    // SUPPORT TICKET

    'SUPPORT_TICKET_CREATED' |

    'SUPPORT_TICKET_COMMENT_CREATED' |

    'SUPPORT_TICKET_ATTACHMENT_CREATED' |

    // VPG

    'VPG_LIVE_FAILOVER_START' |

    'VPG_TEST_FAILOVER_STOP' |

    'VPG_LIVE_FAILOVER_ROLLBACK_FAILED' |

    'VPG_LIVE_FAILOVER_COMMIT_FAILED' |

    'VPG_LIVE_FAILOVER_COMMIT' |

    // DISK

    'DISK_DETACH' |

    'DISK_CREATE_REQUEST' |

    'DISK_DELETE_REQUEST' |

    'DR_RUNBOOK_CREATE' |

    'DR_RUNBOOK_UPDATE' |

    'DR_RUNBOOK_DELETE' |

    'USER_CREATE' |

    'USER_DELETE';
