import { VmCopyMoveVmVnicRequestJson } from './__json__/vm-json';
import { IpAddressingModeType } from '../common/__json__/ip-adressing-mode-type';

/* istanbul ignore next: autogenerated */
export class VmCopyMoveVmVnicRequest {

  private readonly _json: VmCopyMoveVmVnicRequestJson;

  constructor(vmCopyMoveVmVnicRequest: VmCopyMoveVmVnicRequest);
  constructor(vmCopyMoveVmVnicRequestJson: VmCopyMoveVmVnicRequestJson);
  constructor(index: number, networkName: string, isPrimary: boolean, ipAddress: string,
              ipAddressingMode: IpAddressingModeType);
  constructor(firstParam: number | VmCopyMoveVmVnicRequest | VmCopyMoveVmVnicRequestJson, networkName?: string,
              isPrimary?: boolean, ipAddress?: string, ipAddressingMode?: IpAddressingModeType) {
    if (typeof firstParam === 'number') {
      // Parameters constructor
      this._json = {
        index: firstParam,
        network_name: networkName,
        is_primary: isPrimary,
        ip_address: ipAddress,
        ip_addressing_mode: ipAddressingMode
      } as VmCopyMoveVmVnicRequestJson;
    } else if (firstParam instanceof VmCopyMoveVmVnicRequest) {
      // Copy constructor
      this._json = (firstParam as VmCopyMoveVmVnicRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VmCopyMoveVmVnicRequestJson;
    }
  }

  /**
   * Get index.
   * @returns {number}
   */
  get index(): number {
    return this._json.index;
  }

  /**
   * Get network name.
   * @returns {string}
   */
  get networkName(): string {
    return this._json.network_name;
  }

  /**
   * Get is primary.
   * @returns {boolean}
   */
  get isPrimary(): boolean {
    return this._json.is_primary;
  }

  /**
   * Get ip address.
   * @returns {string}
   */
  get ipAddress(): string {
    return this._json.ip_address;
  }

  /**
   * Get ip addressing mode.
   * @returns {IpAddressingModeType}
   */
  get ipAddressingMode(): IpAddressingModeType {
    return this._json.ip_addressing_mode;
  }

  /**
   * Get the json representation of this class.
   * @returns {VmCopyMoveVmVnicRequestJson}
   */
  get json(): VmCopyMoveVmVnicRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
