import { DistributedFirewallRuleServiceObjectJson } from './__json__/distributed-firewall-rule-service-object-json';

/* istanbul ignore next: autogenerated */
export class DistributedFirewallRuleServiceObject {

  constructor(private _json: DistributedFirewallRuleServiceObjectJson) {
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get value.
   * @returns {string}
   */
  get value(): string {
    return this._json.value;
  }

  /**
   * Get type.
   * @returns {string}
   */
  get type(): string {
    return this._json.type;
  }

  /**
   * Get is valid.
   * @returns {boolean}
   */
  get isValid(): boolean {
    return this._json.is_valid;
  }

  /**
   * Get the json representation of this class.
   * @returns {DistributedFirewallRuleServiceObjectJson}
   */
  get json(): DistributedFirewallRuleServiceObjectJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
