import { DistributedFirewallRuleServiceProtocolJson } from './__json__/distributed-firewall-rule-service-protocol-json';
import { DistributedFirewallProtocolNameType } from './distributed-firewall-protocol-name-type';

/* istanbul ignore next: autogenerated */
export class DistributedFirewallRuleServiceProtocol {

  constructor(private _json: DistributedFirewallRuleServiceProtocolJson) {
  }

  /**
   * Get is valid.
   * @returns {boolean}
   */
  get isValid(): boolean {
    return this._json.is_valid;
  }

  /**
   * Get source port.
   * @returns {number}
   */
  get sourcePort(): number {
    return this._json.source_port;
  }

  /**
   * Get destination port.
   * @returns {number}
   */
  get destinationPort(): number {
    return this._json.destination_port;
  }

  /**
   * Get protocol.
   * @returns {number}
   */
  get protocol(): number {
    return this._json.protocol;
  }

  /**
   * Get protocol name.
   * @returns {DistributedFirewallProtocolNameType}
   */
  get protocolName(): DistributedFirewallProtocolNameType {
    return this._json.protocol_name;
  }

  /**
   * Get the json representation of this class.
   * @returns {DistributedFirewallRuleServiceProtocolJson}
   */
  get json(): DistributedFirewallRuleServiceProtocolJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
