import { DistributedFirewallLayer3Json } from './__json__/distributed-firewall-layer3-json';
import { DistributedFirewallLayer3Rule } from './distributed-firewall-layer3-rule';

/**
 * Distributed Firewall Layer 3 Object (General).
 */
/* istanbul ignore next: autogenerated */
export class DistributedFirewallLayer3 {

  constructor(private _json: DistributedFirewallLayer3Json) {
  }

  /**
   * Get rules.
   * @returns {Array<DistributedFirewallLayer3Rule>}
   */
  get rules(): Array<DistributedFirewallLayer3Rule> {
    return (this._json.rules || []).map(it => new DistributedFirewallLayer3Rule(it));
  }

  /**
   * Get id.
   * @returns {number}
   */
  get id(): number {
    return this._json.id;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get generation number.
   * @returns {number}
   */
  get generationNumber(): number {
    return this._json.generation_number;
  }

  /**
   * Get timestamp.
   * @returns {number}
   */
  get timestamp(): number {
    return this._json.timestamp;
  }

  /**
   * Get tcp strict.
   * @returns {boolean}
   */
  get tcpStrict(): boolean {
    return this._json.tcp_strict;
  }

  /**
   * Get stateless.
   * @returns {boolean}
   */
  get stateless(): boolean {
    return this._json.stateless;
  }

  /**
   * Get use sid.
   * @returns {boolean}
   */
  get useSid(): boolean {
    return this._json.use_sid;
  }

  /**
   * Get type.
   * @returns {string}
   */
  get type(): string {
    return this._json.type;
  }

  /**
   * Get the json representation of this class.
   * @returns {DistributedFirewallLayer3Json}
   */
  get json(): DistributedFirewallLayer3Json {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
