import { DistributedFirewallLayer2RuleJson } from './__json__/distributed-firewall-layer2-rule-json';
import { DistributedFirewallActionType } from './distributed-firewall-action-type';
import { DistributedFirewallRuleAppliedTo } from './distributed-firewall-rule-applied-to';
import { DistributedFirewallRuleSource } from './distributed-firewall-rule-source';
import { DistributedFirewallRuleDestination } from './distributed-firewall-rule-destination';
import { DistributedFirewallRuleServiceObject } from './distributed-firewall-rule-service-object';
import { DistributedFirewallRuleServiceProtocol } from './distributed-firewall-rule-service-protocol';
import { DistributedFirewallDirectionType } from './distributed-firewall-direction-type';
import { DistributedFirewallPacketType } from './distributed-firewall-packet-type';

/* istanbul ignore next: autogenerated */
export class DistributedFirewallLayer2Rule {

  constructor(private _json: DistributedFirewallLayer2RuleJson) {
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get action.
   * @returns {DistributedFirewallActionType}
   */
  get action(): DistributedFirewallActionType {
    return this._json.action;
  }

  /**
   * Get applied to list.
   * @returns {Array<DistributedFirewallRuleAppliedTo>}
   */
  get appliedToList(): Array<DistributedFirewallRuleAppliedTo> {
    return (this._json.applied_to_list || []).map(it => new DistributedFirewallRuleAppliedTo(it));
  }

  /**
   * Get section id.
   * @returns {number}
   */
  get sectionId(): number {
    return this._json.section_id;
  }

  /**
   * Get sources excluded.
   * @returns {boolean}
   */
  get sourcesExcluded(): boolean {
    return this._json.sources_excluded;
  }

  /**
   * Get sources.
   * @returns {Array<DistributedFirewallRuleSource>}
   */
  get sources(): Array<DistributedFirewallRuleSource> {
    return (this._json.sources || []).map(it => new DistributedFirewallRuleSource(it));
  }

  /**
   * Get destinations excluded.
   * @returns {boolean}
   */
  get destinationsExcluded(): boolean {
    return this._json.destinations_excluded;
  }

  /**
   * Get destinations.
   * @returns {Array<DistributedFirewallRuleDestination>}
   */
  get destinations(): Array<DistributedFirewallRuleDestination> {
    return (this._json.destinations || []).map(it => new DistributedFirewallRuleDestination(it));
  }

  /**
   * Get service objects.
   * @returns {Array<DistributedFirewallRuleServiceObject>}
   */
  get serviceObjects(): Array<DistributedFirewallRuleServiceObject> {
    return (this._json.service_objects || []).map(it => new DistributedFirewallRuleServiceObject(it));
  }

  /**
   * Get service protocols.
   * @returns {Array<DistributedFirewallRuleServiceProtocol>}
   */
  get serviceProtocols(): Array<DistributedFirewallRuleServiceProtocol> {
    return (this._json.service_protocols || []).map(it => new DistributedFirewallRuleServiceProtocol(it));
  }

  /**
   * Get direction.
   * @returns {DistributedFirewallDirectionType}
   */
  get direction(): DistributedFirewallDirectionType {
    return this._json.direction;
  }

  /**
   * Get packet type.
   * @returns {DistributedFirewallPacketType}
   */
  get packetType(): DistributedFirewallPacketType {
    return this._json.packet_type;
  }

  /**
   * Get tag.
   * @returns {string}
   */
  get tag(): string {
    return this._json.tag;
  }

  /**
   * Get id.
   * @returns {number}
   */
  get id(): number {
    return this._json.id;
  }

  /**
   * Get disabled.
   * @returns {boolean}
   */
  get disabled(): boolean {
    return this._json.disabled;
  }

  /**
   * Get logged.
   * @returns {boolean}
   */
  get logged(): boolean {
    return this._json.logged;
  }

  /**
   * Get the json representation of this class.
   * @returns {DistributedFirewallLayer2RuleJson}
   */
  get json(): DistributedFirewallLayer2RuleJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
