import { DistributedFirewallRestorePointDetailsJson } from './__json__/distributed-firewall-restore-point-details-json';
import { DistributedFirewallLayer3 } from './distributed-firewall-layer3';

/* istanbul ignore next: autogenerated */
export class DistributedFirewallLayer3RestorePointDetails {

  constructor(private _json: DistributedFirewallRestorePointDetailsJson) {
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get restore point time.
   * @returns {number}
   */
  get restorePointTime(): number {
    return this._json.restore_point_time;
  }

  /**
   * Get data.
   * @returns {DistributedFirewallLayer3}
   */
  get data(): DistributedFirewallLayer3 {
    return new DistributedFirewallLayer3(this._json.data);
  }

  /**
   * Get the json representation of this class.
   * @returns {DistributedFirewallRestorePointDetailsJson}
   */
  get json(): DistributedFirewallRestorePointDetailsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
