import {
    GroupResponse,
    PartialOrgResponse,
    SelectedExcludedItems,
    SharePointSiteResponse,
    UserResponse
} from './o365-job-json';

/**
 * O365 Backup Job selected or excluded items class
 */
/* istanbul ignore next: autogenerated */
export class O365BackupJobSelectedExcludedItems {

  constructor(private _json: SelectedExcludedItems) {
  }

  /**
   * Get the O365 Backup Job selected or excluded partial org responses
   */
  get partialOrgResponses(): Array<PartialOrgResponse> {
    return this._json.partial_org_responses;
  }

  /**
   * Get the O365 Backup Job selected or excluded Group responses
   */
  get groupResponses(): Array<GroupResponse> {
    return this._json.group_responses;
  }

  /**
   * Get the O365 Backup Job selected or excluded User responses
   */
  get userResponses(): Array<UserResponse> {
    return this._json.user_responses;
  }

  /**
   * Get the O365 Backup Job selected or excluded SharePoint site responses
   */
  get sitesResponses(): Array<SharePointSiteResponse> {
    return this._json.share_point_site_responses;
  }

  /**
   * Get the json representation of this class.
   * @returns {SelectedExcludedItems}
   */
  get json(): SelectedExcludedItems {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
