import { EdgeGatewaySslVpnServerSettingsJson } from './__json__/edge-gateway-ssl-vpn-server-settings-json';
import { EdgeGatewaySslVpnCipherType } from './edge-gateway-ssl-vpn-cipher-type';

/* istanbul ignore next: autogenerated */
export class EdgeGatewaySslVpnServerSettings {

  constructor(private _json: EdgeGatewaySslVpnServerSettingsJson) {
  }

  /**
   * Get ip address.
   * @returns {string}
   */
  get ipAddress(): string {
    return this._json.ip_address;
  }

  /**
   * Get port.
   * @returns {number}
   */
  get port(): number {
    return this._json.port;
  }

  /**
   * Get certificate id.
   * @returns {string}
   */
  get certificateId(): string {
    return this._json.certificate_id;
  }

  /**
   * Get cipher list.
   * @returns {Array<EdgeGatewaySslVpnCipherType>}
   */
  get cipherList(): Array<EdgeGatewaySslVpnCipherType> {
    return this._json.cipher_list;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewaySslVpnServerSettingsJson}
   */
  get json(): EdgeGatewaySslVpnServerSettingsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
