import { EdgeGatewaySslVpnPasswordPolicyJson } from './__json__/edge-gateway-ssl-vpn-password-policy-json';

/* istanbul ignore next: autogenerated */
export class EdgeGatewaySslVpnPasswordPolicy {

  constructor(private _json: EdgeGatewaySslVpnPasswordPolicyJson) {
  }

  /**
   * Get min length.
   * @returns {number}
   */
  get minLength(): number {
    return this._json.min_length;
  }

  /**
   * Get max length.
   * @returns {number}
   */
  get maxLength(): number {
    return this._json.max_length;
  }

  /**
   * Get min alphabets.
   * @returns {number}
   */
  get minAlphabets(): number {
    return this._json.min_alphabets;
  }

  /**
   * Get min digits.
   * @returns {number}
   */
  get minDigits(): number {
    return this._json.min_digits;
  }

  /**
   * Get min special char.
   * @returns {number}
   */
  get minSpecialChar(): number {
    return this._json.min_special_char;
  }

  /**
   * Get allow user id within password.
   * @returns {boolean}
   */
  get allowUserIdWithinPassword(): boolean {
    return this._json.allow_user_id_within_password;
  }

  /**
   * Get password life time.
   * @returns {number}
   */
  get passwordLifeTime(): number {
    return this._json.password_life_time;
  }

  /**
   * Get expiry notification.
   * @returns {number}
   */
  get expiryNotification(): number {
    return this._json.expiry_notification;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewaySslVpnPasswordPolicyJson}
   */
  get json(): EdgeGatewaySslVpnPasswordPolicyJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
