import { EdgeGatewaySslVpnAuthServerJson } from './__json__/edge-gateway-ssl-vpn-auth-server-json';
import { EdgeGatewaySslVpnLocalAuthServerJson } from './__json__/edge-gateway-ssl-vpn-local-auth-server-json';
import { EdgeGatewaySslVpnAccountLockoutPolicy } from './edge-gateway-ssl-vpn-account-lockout-policy';
import { EdgeGatewaySslVpnAuthServer } from './edge-gateway-ssl-vpn-auth-server';
import { EdgeGatewaySslVpnAuthServerType } from './edge-gateway-ssl-vpn-auth-server-type';
import { EdgeGatewaySslVpnPasswordPolicy } from './edge-gateway-ssl-vpn-password-policy';

/* istanbul ignore next: autogenerated */
export class EdgeGatewaySslVpnLocalAuthServer extends EdgeGatewaySslVpnAuthServer {

  constructor(private _json: EdgeGatewaySslVpnLocalAuthServerJson) {
    super(_json);
  }

  /**
   * Get object id.
   * @returns {string}
   */
  get objectId(): string {
    return this._json.object_id;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get secondary auth server.
   * @returns {boolean}
   */
  get secondaryAuthServer(): boolean {
    return this._json.secondary_auth_server;
  }

  /**
   * Get terminate session on auth fails.
   * @returns {boolean}
   */
  get terminateSessionOnAuthFails(): boolean {
    return this._json.terminate_session_on_auth_fails;
  }

  /**
   * Get password policy.
   * @returns {EdgeGatewaySslVpnPasswordPolicy | null}
   */
  get passwordPolicy(): EdgeGatewaySslVpnPasswordPolicy | null {
    return this._json.password_policy ? new EdgeGatewaySslVpnPasswordPolicy(this._json.password_policy) : null;
  }

  /**
   * Get account lockout policy.
   * @returns {AccountLockoutPolicy | null}
   */
  get accountLockoutPolicy(): EdgeGatewaySslVpnAccountLockoutPolicy | null {
    return this._json.account_lockout_policy ?
        new EdgeGatewaySslVpnAccountLockoutPolicy(this._json.account_lockout_policy) : null;
  }

  /**
   * Get auth server type.
   * @returns {EdgeGatewaySslVpnAuthServerType}
   */
  get authServerType(): EdgeGatewaySslVpnAuthServerType {
    return this._json.auth_server_type;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewaySslVpnLocalAuthServerJson}
   */
  get json(): EdgeGatewaySslVpnLocalAuthServerJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
