import { EdgeGatewaySslVpnLdapAuthServerJson } from './__json__/edge-gateway-ssl-vpn-ldap-auth-server-json';
import { EdgeGatewaySslVpnAuthServer } from './edge-gateway-ssl-vpn-auth-server';
import { EdgeGatewaySslVpnAuthServerType } from './edge-gateway-ssl-vpn-auth-server-type';

/* istanbul ignore next: autogenerated */
export class EdgeGatewaySslVpnLdapAuthServer extends EdgeGatewaySslVpnAuthServer {

  constructor(private _json: EdgeGatewaySslVpnLdapAuthServerJson) {
    super(_json);
  }

  /**
   * Get object id.
   * @returns {string}
   */
  get objectId(): string {
    return this._json.object_id;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get secondary auth server.
   * @returns {boolean}
   */
  get secondaryAuthServer(): boolean {
    return this._json.secondary_auth_server;
  }

  /**
   * Get terminate session on auth fails.
   * @returns {boolean}
   */
  get terminateSessionOnAuthFails(): boolean {
    return this._json.terminate_session_on_auth_fails;
  }

  /**
   * Get enable ssl.
   * @returns {boolean}
   */
  get enableSsl(): boolean {
    return this._json.enable_ssl;
  }

  /**
   * Get ip.
   * @returns {string}
   */
  get ip(): string {
    return this._json.ip;
  }

  /**
   * Get port.
   * @returns {number}
   */
  get port(): number {
    return this._json.port;
  }

  /**
   * Get timeout.
   * @returns {number}
   */
  get timeout(): number {
    return this._json.timeout;
  }

  /**
   * Get search base.
   * @returns {string}
   */
  get searchBase(): string {
    return this._json.search_base;
  }

  /**
   * Get bind domain name.
   * @returns {string}
   */
  get bindDomainName(): string {
    return this._json.bind_domain_name;
  }

  /**
   * Get bind password.
   * @returns {string}
   */
  get bindPassword(): string {
    return this._json.bind_password;
  }

  /**
   * Get login attribute name.
   * @returns {string}
   */
  get loginAttributeName(): string {
    return this._json.login_attribute_name;
  }

  /**
   * Get search filter.
   * @returns {string}
   */
  get searchFilter(): string {
    return this._json.search_filter;
  }

  /**
   * Get certificate sha1 digest.
   * @returns {string}
   */
  get certificateSha1Digest(): string {
    return this._json.certificate_sha1_digest;
  }

  /**
   * Get auth server type.
   * @returns {EdgeGatewaySslVpnAuthServerType}
   */
  get authServerType(): EdgeGatewaySslVpnAuthServerType {
    return this._json.auth_server_type;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewaySslVpnLdapAuthServerJson}
   */
  get json(): EdgeGatewaySslVpnLdapAuthServerJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
