import { X509CertificateJson } from './__json__/x509-certificate-json';

/* istanbul ignore next: autogenerated */
export class X509Certificate {

  constructor(private _json: X509CertificateJson) {
  }

  /**
   * Get subject cn.
   * @returns {string}
   */
  get subjectCn(): string {
    return this._json.subject_cn;
  }

  /**
   * Get issuer cn.
   * @returns {string}
   */
  get issuerCn(): string {
    return this._json.issuer_cn;
  }

  /**
   * Get version.
   * @returns {number}
   */
  get version(): number {
    return this._json.version;
  }

  /**
   * Get serial number.
   * @returns {string}
   */
  get serialNumber(): string {
    return this._json.serial_number;
  }

  /**
   * Get signature algo name.
   * @returns {string}
   */
  get signatureAlgoName(): string {
    return this._json.signature_algo_name;
  }

  /**
   * Get signature.
   * @returns {string}
   */
  get signature(): string {
    return this._json.signature;
  }

  /**
   * Get not before.
   * @returns {Date | undefined}
   */
  get notBefore(): Date | undefined {
    if (!this._json.not_before) {
      return undefined;
    }
    return new Date(this._json.not_before);
  }

  /**
   * Get not after.
   * @returns {Date | undefined}
   */
  get notAfter(): Date | undefined {
    if (!this._json.not_after) {
      return undefined;
    }
    return new Date(this._json.not_after);
  }

  /**
   * Get issuer.
   * @returns {string}
   */
  get issuer(): string {
    return this._json.issuer;
  }

  /**
   * Get subject.
   * @returns {string}
   */
  get subject(): string {
    return this._json.subject;
  }

  /**
   * Get public key algo.
   * @returns {string}
   */
  get publicKeyAlgo(): string {
    return this._json.public_key_algo;
  }

  /**
   * Get public key length.
   * @returns {number}
   */
  get publicKeyLength(): number {
    return this._json.public_key_length;
  }

  /**
   * Get rsa public key modulus.
   * @returns {string}
   */
  get rsaPublicKeyModulus(): string {
    return this._json.rsa_public_key_modulus;
  }

  /**
   * Get rsa public key exponent.
   * @returns {number}
   */
  get rsaPublicKeyExponent(): number {
    return this._json.rsa_public_key_exponent;
  }

  /**
   * Get sha1 hash.
   * @returns {string}
   */
  get sha1Hash(): string {
    return this._json.sha1_hash;
  }

  /**
   * Get md5 hash.
   * @returns {string}
   */
  get md5Hash(): string {
    return this._json.md5_hash;
  }

  /**
   * Get is ca.
   * @returns {boolean}
   */
  get isCa(): boolean {
    return this._json.is_ca;
  }

  /**
   * Get is valid.
   * @returns {boolean}
   */
  get isValid(): boolean {
    return this._json.is_valid;
  }

  /**
   * Get the json representation of this class.
   * @returns {X509CertificateJson}
   */
  get json(): X509CertificateJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
