import { AccountEventJson } from './__json__/account-even-json';

/**
 * Account Event.
 */
/* istanbul ignore next: autogenerated */
export class AccountEvent {

  constructor(private _json: AccountEventJson) {
  }

  /**
   * Get time.
   * @returns {number}
   */
  get time(): number {
    return this._json.time;
  }

  /**
   * Get type.
   * @returns {string}
   */
  get type(): string {
    return this._json.type;
  }

  /**
   * Get client name.
   * @returns {string}
   */
  get clientName(): string {
    return this._json.client_name;
  }

  /**
   * Get user id.
   * @returns {string}
   */
  get userId(): string {
    return this._json.user_id;
  }

  /**
   * Get session id.
   * @returns {string}
   */
  get sessionId(): string {
    return this._json.session_id;
  }

  /**
   * Get ip address.
   * @returns {string}
   */
  get ipAddress(): string {
    return this._json.ip_address;
  }

  /**
   * Get error.
   * @returns {string}
   */
  get error(): string {
    return this._json.error;
  }

  /**
   * Get details.
   * @returns {{ [key: string]: string }}
   */
  get details(): { [key: string]: string } {
    return this._json.details;
  }

  /**
   * Get the json representation of this class.
   * @returns {AccountEventJson}
   */
  get json(): AccountEventJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
