"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
/**
 * Inbox Message.
 */
/* istanbul ignore next: autogenerated */
var InboxMessage = (function () {
    function InboxMessage(_json) {
        this._json = _json;
    }
    Object.defineProperty(InboxMessage.prototype, "uuid", {
        /**
         * Get uuid.
         * @returns {string}
         */
        get: function () {
            return this._json.uuid;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "subject", {
        /**
         * Get subject.
         * @returns {string}
         */
        get: function () {
            return this._json.subject;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "content", {
        /**
         * Get content.
         * @returns {string}
         */
        get: function () {
            return this._json.content;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "hash", {
        /**
         * Get hash.
         * @returns {string}
         */
        get: function () {
            return this._json.hash;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "folder", {
        /**
         * Get folder.
         * @returns {MessageFolder}
         */
        get: function () {
            return this._json.folder;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "read", {
        /**
         * Get read.
         * @returns {boolean}
         */
        get: function () {
            return this._json.read;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "time", {
        /**
         * Get time.
         * @returns {number}
         */
        get: function () {
            return this._json.time;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "username", {
        /**
         * Get username.
         * @returns {string}
         */
        get: function () {
            return this._json.username;
        },
        enumerable: true,
        configurable: true
    });
    Object.defineProperty(InboxMessage.prototype, "json", {
        /**
         * Get the json representation of this class.
         * @returns {InboxMessageJson}
         */
        get: function () {
            return Object.assign({}, this._json);
        },
        enumerable: true,
        configurable: true
    });
    /**
     * Get the string representation of this class.
     * @returns {string}
     */
    InboxMessage.prototype.toString = function () {
        return JSON.stringify(this._json, undefined, 2);
    };
    return InboxMessage;
}());
exports.InboxMessage = InboxMessage;
