import { InboxMessageListJson } from './__json__/inbox-message-list-json';
import { InboxMessageFilterParams } from './inbox-message-filter-params';
import { InboxMessage } from './inbox-message';

/**
 * Inbox Message List.
 */
/* istanbul ignore next: autogenerated */
export class InboxMessageList {

  constructor(private _json: InboxMessageListJson) {
  }

  /**
   * Get current page parameters.
   * @returns {InboxMessageFilterParams}
   */
  get currentPageParameters(): InboxMessageFilterParams {
    return this._json.current_page_parameters;
  }

  /**
   * Get next page parameters.
   * @returns {InboxMessageFilterParams}
   */
  get nextPageParameters(): InboxMessageFilterParams {
    return this._json.next_page_parameters;
  }

  /**
   * Get total records.
   * @returns {number}
   */
  get totalRecords(): number {
    return this._json.total_records;
  }

  /**
   * Get last page.
   * @returns {boolean}
   */
  get lastPage(): boolean {
    return this._json.last_page;
  }

  /**
   * Get data.
   * @returns {Array<InboxMessage>}
   */
  get data(): Array<InboxMessage> {
    return this._json.data.map(it => new InboxMessage(it));
  }

  /**
   * Get the json representation of this class.
   * @returns {InboxMessageListJson}
   */
  get json(): InboxMessageListJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
