export type ReportTypeJson = 'ANTIMALWARE' |
    'CONTINUITY_PROTECTION' |
    'DISASTER_RECOVERY_ADMIN' |
    'DPI_EVENT' |
    'CLOUD_EVENT_HISTORY' |
    'FIREWALL_EVENT' |
    'HIPAA' |
    'INTEGRITY_EVENT' |
    'LOG_INSPECTION_EVENT' |
    'LOGIN_EVENT_HISTORY' |
    'SUPPORT_REQUESTS' |
    'VM_ENCRYPTION' |
    'ORG_VM_INVENTORY' |
    'VDC_VM_INVENTORY' |
    'VULNERABILITY' |
    'ORG_BILLING_REPORT' |
    'WEB_REPUTATION_EVENT';
