import { VappTemplateUpdateRequestJson } from './__json__';

/**
 * Vapp Template Update Request.
 */
/* istanbul ignore next: autogenerated */
export class VappTemplateUpdateRequest {

  private readonly _json: VappTemplateUpdateRequestJson;

  constructor(vappTemplateUpdateRequest: VappTemplateUpdateRequest);
  constructor(vappTemplateUpdateRequestJson: VappTemplateUpdateRequestJson);
  constructor(name: string, description: string);
  constructor(firstParam: string | VappTemplateUpdateRequest | VappTemplateUpdateRequestJson, description?: string) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        name: firstParam,
        description: description
      } as VappTemplateUpdateRequestJson;
    } else if (firstParam instanceof VappTemplateUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as VappTemplateUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VappTemplateUpdateRequestJson;
    }
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get the json representation of this class.
   * @returns {VappTemplateUpdateRequestJson}
   */
  get json(): VappTemplateUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
