import { VappTemplateVmJson } from './__json__/vapp-template-vm-json';

/* istanbul ignore next: autogenerated */
export class VappTemplateVm {

  constructor(private _json: VappTemplateVmJson) {
  }

  /**
   * Get status.
   * @returns {number}
   */
  get status(): number {
    return this._json.status;
  }

  /**
   * Get size.
   * @returns {number}
   */
  get size(): number {
    return this._json.size;
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get fullname.
   * @returns {string}
   */
  get fullname(): string {
    return this._json.fullname;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get vcloud href.
   * @returns {string}
   */
  get vcloudHref(): string {
    return this._json.vcloud_href;
  }

  /**
   * Get deleted.
   * @returns {boolean}
   */
  get deleted(): boolean {
    return this._json.deleted;
  }

  /**
   * Get created date.
   * @returns {number}
   */
  get createdDate(): number {
    return this._json.created_date;
  }

  /**
   * Get deleted date.
   * @returns {number}
   */
  get deletedDate(): number {
    return this._json.deleted_date;
  }

  /**
   * Get the json representation of this class.
   * @returns {VappTemplateVmJson}
   */
  get json(): VappTemplateVmJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
