import { VccFailoverStartCreateRequestJson } from './__json__/vcc-failover-start-request-json';

/**
 * VccFailoverStartCreateRequest.
 */
/* istanbul ignore next: autogenerated */
export class VccFailoverStartCreateRequest {

  private readonly _json: VccFailoverStartCreateRequestJson;

  constructor(vccFailoverStartCreateRequest: VccFailoverStartCreateRequest);
  constructor(vccFailoverStartCreateRequestJson: VccFailoverStartCreateRequestJson);
  constructor(startDate: number | undefined);
  constructor(firstParam: number | undefined | VccFailoverStartCreateRequest | VccFailoverStartCreateRequestJson) {
    if (firstParam === undefined || typeof firstParam === 'number') {
      // Parameters constructor
      this._json = {
        start_date: firstParam
      } as VccFailoverStartCreateRequestJson;
    } else if (firstParam instanceof VccFailoverStartCreateRequest) {
      // Copy constructor
      this._json = (firstParam as VccFailoverStartCreateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VccFailoverStartCreateRequestJson;
    }
  }

  /**
   * Get start date.
   * @returns {number}
   */
  get startDate(): number | undefined {
    return this._json.start_date;
  }

  /**
   * Get the json representation of this class.
   * @returns {VccFailoverStartCreateRequestJson}
   */
  get json(): VccFailoverStartCreateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
