import { NetworkSubAllocationJson } from './__json__';
import { IpRangeJson } from './ip-range/__json__';

/* istanbul ignore next: autogenerated */
export class NetworkSubAllocation {
  constructor(private _json: NetworkSubAllocationJson) {
  }

  /**
   * Get edge name.
   * @returns {string}
   */
  get edgeName(): string {
    return this._json.edge_name;
  }

  /**
   * Get ip ranges.
   * @returns {Array<IpRangeJson>}
   */
  get ipRanges(): Array<IpRangeJson> {
    return this._json.ip_ranges;
  }

  /**
   * Get the json representation of this class.
   * @returns {NetworkSubAllocationJson}
   */
  get json(): NetworkSubAllocationJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
