import { PerformanceCounterJson } from './__json__/performance-counter-json';

/**
 * Performance Counter.
 */
/* istanbul ignore next: autogenerated */
export class PerformanceCounter {

  constructor(private _json: PerformanceCounterJson) {
  }

    /**
     * Get group.
     * @returns {string}
     */
  get group(): string {
    return this._json.group;
  }

    /**
     * Get name.
     * @returns {string}
     */
  get name(): string {
    return this._json.name;
  }

    /**
     * Get type.
     * @returns {string}
     */
  get type(): string {
    return this._json.type;
  }

    /**
     * Get the json representation of this class.
     * @returns {PerformanceCounterJson}
     */
  get json(): PerformanceCounterJson {
    return Object.assign({}, this._json);
  }

    /**
     * Get the string representation of this class.
     * @returns {string}
     */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
