import { EdgeGatewayFirewallActionType } from './__json__/edge-gateway-firewall-action-type';
import { EdgeGatewayFirewallRuleJson } from './__json__/edge-gateway-firewall-rule-json';
import { EdgeGatewayFirewallRuleApplication } from './edge-gateway-firewall-rule-application';
import { EdgeGatewayFirewallRuleSourceDestination } from './edge-gateway-firewall-rule-source-destination';

/**
 * Firewall Rule
 */
/* istanbul ignore next: autogenerated */
export class EdgeGatewayFirewallRule {

  constructor(private _json: EdgeGatewayFirewallRuleJson) {}

  /**
   * Get id.
   * @returns {number}
   */
  get id(): number {
    return this._json.id;
  }

  /**
   * Get rule tag.
   * @returns {number}
   */
  get ruleTag(): number {
    return this._json.rule_tag;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get rule type.
   * @returns {string}
   */
  get ruleType(): string {
    return this._json.rule_type;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get source.
   * @returns {EdgeGatewayFirewallRuleSourceDestination}
   */
  get source(): EdgeGatewayFirewallRuleSourceDestination {
    return new EdgeGatewayFirewallRuleSourceDestination(this._json.source);
  }

  /**
   * Get destination.
   * @returns {EdgeGatewayFirewallRuleSourceDestination}
   */
  get destination(): EdgeGatewayFirewallRuleSourceDestination {
    return new EdgeGatewayFirewallRuleSourceDestination(this._json.destination);
  }

  /**
   * Get application.
   * @returns {EdgeGatewayFirewallRuleApplication}
   */
  get application(): EdgeGatewayFirewallRuleApplication {
    return new EdgeGatewayFirewallRuleApplication(this._json.application);
  }

  /**
   * Get action type.
   * @returns {EdgeGatewayFirewallActionType}
   */
  get actionType(): EdgeGatewayFirewallActionType {
    return this._json.action_type;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get logging enabled.
   * @returns {boolean}
   */
  get loggingEnabled(): boolean {
    return this._json.logging_enabled;
  }

  /**
   * Get match translated.
   * @returns {boolean}
   */
  get matchTranslated(): boolean {
    return this._json.match_translated;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayFirewallRuleJson}
   */
  get json(): EdgeGatewayFirewallRuleJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
