import { EdgeGatewayFirewallJson } from './__json__/edge-gateway-firewall-json';
import { EdgeGatewayFirewallDefaultPolicy } from './edge-gateway-firewall-default-policy';
import { EdgeGatewayFirewallGlobalConfig } from './edge-gateway-firewall-global-config';
import { EdgeGatewayFirewallRule } from './edge-gateway-firewall-rule';

/**
 * Firewall Class
 */
/* istanbul ignore next: autogenerated */
export class EdgeGatewayFirewall {

  constructor(private _json: EdgeGatewayFirewallJson) {}

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get firewall global config.
   * @returns {EdgeGatewayFirewallGlobalConfig}
   */
  get firewallGlobalConfig(): EdgeGatewayFirewallGlobalConfig {
    return new EdgeGatewayFirewallGlobalConfig(this._json.firewall_global_config);
  }

  /**
   * Get firewall default policy.
   * @returns {EdgeGatewayFirewallDefaultPolicy}
   */
  get firewallDefaultPolicy(): EdgeGatewayFirewallDefaultPolicy {
    return new EdgeGatewayFirewallDefaultPolicy(this._json.firewall_default_policy);
  }

  /**
   * Get firewall rules.
   * @returns {Array<EdgeGatewayFirewallRule>}
   */
  get firewallRules(): Array<EdgeGatewayFirewallRule> {
    return this._json.firewall_rules.map(rule => new EdgeGatewayFirewallRule(rule));
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayFirewallJson}
   */
  get json(): EdgeGatewayFirewallJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
