import { GatewayNatRuleJson } from './__json__/gateway-nat-rule-json';

/**
 * GatewayNatRule class
 */
/* istanbul ignore next: autogenerated */
export class GatewayNatRule {

  constructor(private _json: GatewayNatRuleJson) {
  }

  /**
   * Get description.
   * @returns {string | null}
   */
  get description(): string | null {
    return this._json.description;
  }

  /**
   * Get id.
   * @returns {number}
   */
  get id(): number {
    return this._json.id;
  }

  /**
   * Get rule type.
   * @returns {string}
   */
  get ruleType(): string {
    return this._json.rule_type;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get icmp sub type.
   * @returns {string | null}
   */
  get icmpSubType(): string | null {
    return this._json.icmp_sub_type;
  }

  /**
   * Get original ip.
   * @returns {string}
   */
  get originalIp(): string {
    return this._json.original_ip;
  }

  /**
   * Get original port.
   * @returns {string | null}
   */
  get originalPort(): string | null {
    return this._json.original_port;
  }

  /**
   * Get protocol.
   * @returns {string | null}
   */
  get protocol(): string | null {
    return this._json.protocol;
  }

  /**
   * Get translated ip.
   * @returns {string}
   */
  get translatedIp(): string {
    return this._json.translated_ip;
  }

  /**
   * Get translated port.
   * @returns {string | null}
   */
  get translatedPort(): string | null {
    return this._json.translated_port;
  }

  /**
   * Get interface name.
   * @returns {string}
   */
  get interfaceName(): string {
    return this._json.interface_name;
  }

  /**
   * Get rule index.
   * @returns {number}
   */
  get ruleIndex(): number {
    return this._json.rule_index;
  }

  /**
   * Get the json representation of this class.
   * @returns {GatewayNatRuleJson}
   */
  get json(): GatewayNatRuleJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
