import { EdgeGatewayIpsecTunnelInterfaceJson } from './__json__/edge-gateway-ipsec-tunnel-interface-json';

/* istanbul ignore next: autogenerated */
export class EdgeGatewayIpsecTunnelInterface {

  constructor(private _json: EdgeGatewayIpsecTunnelInterfaceJson) {
  }

  /**
   * Get label.
   * @returns {string}
   */
  get label(): string {
    return this._json.label;
  }

  /**
   * Get ip address.
   * @returns {string}
   */
  get ipAddress(): string {
    return this._json.ip_address;
  }

  /**
   * Get mtu.
   * @returns {number}
   */
  get mtu(): number {
    return this._json.mtu;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewayIpsecTunnelInterfaceJson}
   */
  get json(): EdgeGatewayIpsecTunnelInterfaceJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
