import { BaBackupDirectoryJson } from './__json__/ba-backup-directory-json';

/**
 * BaBackupDirectory class
 */

/* istanbul ignore next: autogenerated */
export class BaBackupDirectory {

  constructor(private _json: BaBackupDirectoryJson) {
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get size mb.
   * @returns {number}
   */
  get sizeMb(): number {
    return this._json.size_mb;
  }

  /**
   * Get modified at.
   * @returns {Date | null}
   */
  get modifiedAt(): Date | null {
    return this._json.modified_at ? new Date(this._json.modified_at) : null;
  }

  /**
   * Get repository name.
   * @returns {string}
   */
  get repositoryName(): string {
    return this._json.repository_name;
  }

  /**
   * Get backup server name.
   * @returns {string}
   */
  get backupServerName(): string {
    return this._json.backup_server_name;
  }

  /**
   * Get recycled.
   * @returns {boolean}
   */
  get recycled(): boolean {
    return this._json.recycled;
  }

  /**
   * Get the json representation of this class.
   * @returns {BaBackupDirectoryJson}
   */
  get json(): BaBackupDirectoryJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
