import { SecondaryAddressesJson } from './__json__/vnic-secondary-addresses-json';

/**
 * Edge Gateway VNIC Secondary Addresses.
 */
/* istanbul ignore next: autogenerated */
export class SecondaryAddresses {

  constructor(private _json: SecondaryAddressesJson) {
  }

  /**
   * Get ip address.
   * @returns {Array<string>}
   */
  get ipAddress(): Array<string> {
    return this._json.ip_address;
  }

  /**
   * Get the json representation of this class.
   * @returns {SecondaryAddresses}
   */
  get json(): SecondaryAddressesJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
