import { VappResourceSummaryJson } from './__json__';

/* istanbul ignore next: autogenerated */
export class VappResourceSummary {

  constructor(private _json: VappResourceSummaryJson) {
  }

  /**
   * Get reserved cpu.
   * @returns {number}
   */
  get reservedCpu(): number {
    return this._json.reserved_cpu;
  }

  /**
   * Get reserved mem.
   * @returns {number}
   */
  get reservedMem(): number {
    return this._json.reserved_mem;
  }

  /**
   * Get consumed cpu.
   * @returns {number}
   */
  get consumedCpu(): number {
    return this._json.consumed_cpu;
  }

  /**
   * Get consumed mem.
   * @returns {number}
   */
  get consumedMem(): number {
    return this._json.consumed_mem;
  }

  /**
   * Get consumed disk.
   * @returns {number}
   */
  get consumedDisk(): number {
    return this._json.consumed_disk;
  }

  /**
   * Get provisioned disk.
   * @returns {number}
   */
  get provisionedDisk(): number {
    return this._json.provisioned_disk;
  }

  /**
   * Get configured disk.
   * @returns {number}
   */
  get configuredDisk(): number {
    return this._json.configured_disk;
  }

  /**
   * Get number of vms.
   * @returns {number}
   */
  get numberOfVms(): number {
    return this._json.number_of_vms;
  }

  /**
   * Get the json representation of this class.
   * @returns {VappResourceSummaryJson}
   */
  get json(): VappResourceSummaryJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
