/**
 * Restore task object status Enum.
 */
export enum RestoreTaskObjectStatus {
  FILES_CLONED = 'FILES_CLONED',
  FETCHED_ENTITY_INFO = 'FETCHED_ENTITY_INFO',
  VM_CREATED = 'VM_CREATED',
  RELOCATION_STARTED = 'RELOCATION_STARTED',
  FINISHED = 'FINISHED',
  ABORTED = 'ABORTED',
  DATA_COPY_STARTED = 'DATA_COPY_STARTED',
  IN_PROGRESS = 'IN_PROGRESS'
}
