import { VdiAutomationGroupJson } from './__json__/vdi-automation-group-json';
import { NetworkConnectionType } from './network-connection-type';

/**
 * VDI Automation Group.
 */
/* istanbul ignore next: autogenerated */
export class VdiAutomationGroup {

  constructor(private _json: VdiAutomationGroupJson) {
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get edge uuid.
   * @returns {string}
   */
  get edgeUuid(): string {
    return this._json.edge_uuid;
  }

  /**
   * Get public ip.
   * @returns {string}
   */
  get publicIp(): string {
    return this._json.public_ip;
  }

  /**
   * Get vapp template uuid.
   * @returns {string}
   */
  get vappTemplateUuid(): string {
    return this._json.vapp_template_uuid;
  }

  /**
   * Get vm template uuid.
   * @returns {string}
   */
  get vmTemplateUuid(): string {
    return this._json.vm_template_uuid;
  }

  /**
   * Get deployment vdc uuid.
   * @returns {string}
   */
  get deploymentVdcUuid(): string {
    return this._json.deployment_vdc_uuid;
  }

  /**
   * Get org vdc network uuid.
   * @returns {string}
   */
  get orgVdcNetworkUuid(): string {
    return this._json.org_vdc_network_uuid;
  }

  /**
   * Get domain to join.
   * @returns {string}
   */
  get domainToJoin(): string {
    return this._json.domain_to_join;
  }

  /**
   * Get team uuid.
   * @returns {string}
   */
  get teamUuid(): string {
    return this._json.team_uuid;
  }

  /**
   * Get network connection type.
   * @returns {NetworkConnectionType}
   */
  get networkConnectionType(): NetworkConnectionType {
    return this._json.network_connection_type;
  }

  /**
   * Get join domain enabled.
   * @returns {boolean}
   */
  get joinDomainEnabled(): boolean {
    return this._json.join_domain_enabled;
  }

  /**
   * Get guest password reset required.
   * @returns {boolean}
   */
  get guestPasswordResetRequired(): boolean {
    return this._json.guest_password_reset_required;
  }

  /**
   * Get the json representation of this class.
   * @returns {VdiAutomationGroupJson}
   */
  get json(): VdiAutomationGroupJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
