import { VdiAutomationDeploymentRequestJson } from './__json__/vdi-automation-deployment-request-json';

/**
 * VDI Automation Deployment Request.
 */
/* istanbul ignore next: autogenerated */
export class VdiAutomationDeploymentRequest {

  private readonly _json: VdiAutomationDeploymentRequestJson;

  constructor(vdiAutomationDeploymentRequest: VdiAutomationDeploymentRequest);
  constructor(vdiAutomationDeploymentRequestJson: VdiAutomationDeploymentRequestJson);
  constructor(vdiUserUuids: Array<string>);
  constructor(firstParam: Array<string> | VdiAutomationDeploymentRequest | VdiAutomationDeploymentRequestJson) {
    if (firstParam instanceof Array) {
      // Parameters constructor
      this._json = {
        vdi_user_uuids: firstParam
      } as VdiAutomationDeploymentRequestJson;
    } else if (firstParam instanceof VdiAutomationDeploymentRequest) {
      // Copy constructor
      this._json = (firstParam as VdiAutomationDeploymentRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VdiAutomationDeploymentRequestJson;
    }
  }

  /**
   * Get vdi user uuids.
   * @returns {Array<string>}
   */
  get vdiUserUuids(): Array<string> {
    return this._json.vdi_user_uuids;
  }

  /**
   * Get the json representation of this class.
   * @returns {VdiAutomationDeploymentRequestJson}
   */
  get json(): VdiAutomationDeploymentRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
