import {
  AutomationGroupConfigJson,
  DeploymentDetailsJson,
  DeploymentUserJson,
  VdiAutomationDeploymentJson
} from './__json__/vdi-automation-deployment-json';
import { NetworkConnectionType } from './network-connection-type';
import { VdiDeploymentState } from './vdi-deployment-state';

/**
 * VDI Automation Deployment.
 */
/* istanbul ignore next: autogenerated */
export class VdiAutomationDeployment {

  constructor(private _json: VdiAutomationDeploymentJson) {
  }

  /**
   * Get uuid.
   * @returns {string}
   */
  get uuid(): string {
    return this._json.uuid;
  }

  /**
   * Get org uuid.
   * @returns {string}
   */
  get orgUuid(): string {
    return this._json.org_uuid;
  }

  /**
   * Get automation group uuid.
   * @returns {string}
   */
  get automationGroupUuid(): string {
    return this._json.automation_group_uuid;
  }

  /**
   * Get state.
   * @returns {VdiDeploymentState}
   */
  get state(): VdiDeploymentState {
    return this._json.state;
  }

  /**
   * Get deployment user.
   * @returns {DeploymentUser}
   */
  get deploymentUser(): DeploymentUser {
    return new DeploymentUser(this._json.deployment_user);
  }

  /**
   * Get configuration.
   * @returns {AutomationGroupConfig}
   */
  get configuration(): AutomationGroupConfig {
    return new AutomationGroupConfig(this._json.configuration);
  }

  /**
   * Get deployment details.
   * @returns {DeploymentDetails}
   */
  get deploymentDetails(): DeploymentDetails {
    return new DeploymentDetails(this._json.deployment_details);
  }

  /**
   * Gets the failure message field.
   * @returns {string | undefined}
   */
  get failureMessage(): string | undefined {
    return this._json.failure_message;
  }

  /**
   * Get the json representation of this class.
   * @returns {VdiAutomationDeploymentJson}
   */
  get json(): VdiAutomationDeploymentJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}

/**
 * Deployment Details.
 */
/* istanbul ignore next: autogenerated */
export class DeploymentDetails {

  constructor(private _json: DeploymentDetailsJson) {
  }

  /**
   * Get internal ip.
   * @returns {string}
   */
  get internalIp(): string {
    return this._json.internal_ip;
  }

  /**
   * Get public rdp port.
   * @returns {string}
   */
  get publicRdpPort(): string {
    return this._json.public_rdp_port;
  }

  /**
   * Get vm uuid.
   * @returns {string}
   */
  get vmUuid(): string {
    return this._json.vm_uuid;
  }

  /**
   * Get vapp uuid.
   * @returns {string}
   */
  get vappUuid(): string {
    return this._json.vapp_uuid;
  }

  /**
   * Get guest admin password.
   * @returns {string}
   */
  get guestAdminPassword(): string {
    return this._json.guest_admin_password;
  }

  /**
   * Get computer name.
   * @returns {string}
   */
  get computerName(): string {
    return this._json.computer_name;
  }

  /**
   * Get the json representation of this class.
   * @returns {DeploymentDetailsJson}
   */
  get json(): DeploymentDetailsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}

/**
 * Deployment User.
 */
/* istanbul ignore next: autogenerated */
export class DeploymentUser {

  constructor(private _json: DeploymentUserJson) {
  }

  /**
   * Get user uuid.
   * @returns {string}
   */
  get userUuid(): string {
    return this._json.user_uuid;
  }

  /**
   * Get user email.
   * @returns {string}
   */
  get userEmail(): string {
    return this._json.user_email;
  }

  /**
   * Get user full name.
   * @returns {string}
   */
  get userFullName(): string {
    return this._json.user_full_name;
  }

  /**
   * Get the json representation of this class.
   * @returns {DeploymentUser}
   */
  get json(): DeploymentUserJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}

/**
 * Deployment Automation Group Config.
 */
/* istanbul ignore next: autogenerated */
export class AutomationGroupConfig {

  constructor(private _json: AutomationGroupConfigJson) {
  }

  /**
   * Get vm template uuid.
   * @returns {string}
   */
  get vmTemplateUuid(): string {
    return this._json.vm_template_uuid;
  }

  /**
   * Get deployment vdc uuid.
   * @returns {string}
   */
  get deploymentVdcUuid(): string {
    return this._json.deployment_vdc_uuid;
  }

  /**
   * Get org vdc network uuid.
   * @returns {string}
   */
  get orgVdcNetworkUuid(): string {
    return this._json.org_vdc_network_uuid;
  }

  /**
   * Get domain to join.
   * @returns {string}
   */
  get domainToJoin(): string {
    return this._json.domain_to_join;
  }

  /**
   * Get edge uuid.
   * @returns {string}
   */
  get edgeUuid(): string {
    return this._json.edge_uuid;
  }

  /**
   * Get public rdp ip.
   * @returns {string}
   */
  get publicRdpIp(): string {
    return this._json.public_rdp_ip;
  }

  /**
   * Get network connection type.
   * @returns {NetworkConnectionType}
   */
  get networkConnectionType(): NetworkConnectionType {
    return this._json.network_connection_type;
  }

  /**
   * Get join domain enabled.
   * @returns {boolean}
   */
  get joinDomainEnabled(): boolean {
    return this._json.join_domain_enabled;
  }

  /**
   * Get guest password reset required.
   * @returns {boolean}
   */
  get guestPasswordResetRequired(): boolean {
    return this._json.guest_password_reset_required;
  }

  /**
   * Get the json representation of this class.
   * @returns {AutomationGroupConfigJson}
   */
  get json(): AutomationGroupConfigJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
