import { VdiTeamUpdateRequestJson } from './__json__/vdi-team-update-request-json';

/**
 * VDI Team Create/Update Request.
 */
/* istanbul ignore next: autogenerated */
export class VdiTeamUpdateRequest {

  private readonly _json: VdiTeamUpdateRequestJson;

  constructor(vdiTeamUpdateRequest: VdiTeamUpdateRequest);
  constructor(vdiTeamUpdateRequestJson: VdiTeamUpdateRequestJson);
  constructor(name: string, members: Array<string>);
  constructor(firstParam: string | VdiTeamUpdateRequest | VdiTeamUpdateRequestJson, members?: Array<string>) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        name: firstParam,
        members: members
      } as VdiTeamUpdateRequestJson;
    } else if (firstParam instanceof VdiTeamUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as VdiTeamUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as VdiTeamUpdateRequestJson;
    }
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get members.
   * @returns {Array<string>}
   */
  get members(): Array<string> {
    return this._json.members;
  }

  /**
   * Get the json representation of this class.
   * @returns {VdiTeamUpdateRequestJson}
   */
  get json(): VdiTeamUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
