export type VdiDeploymentState = 'QUEUED_FOR_DEPLOYMENT' |
    'DEPLOYING' |
    'BOOTING' |
    'CONFIGURING_RDP_ACCESS' |
    'SENDING_USER_ACCESS_NOTIFICATION' |
    'READY' |
    'QUEUED_FOR_UNDEPLOYMENT' |
    'SENDING_USER_UNDEPLOY_NOTIFICATION' |
    'REMOVING_RDP_ACCESS' |
    'POWERING_DOWN' |
    'UNDEPLOYING' |
    'FAILED';
