import { EdgeSslVpnUserJson } from './__json__/edge-ssl-vpn-json';

/**
 * EdgeSslVpnUser class
 */
/* istanbul ignore next: autogenerated */
export class EdgeSslVpnUser {

  constructor(private _json: EdgeSslVpnUserJson) {
  }

  /**
   * Get user id.
   * @returns {string}
   */
  get userId(): string {
    return this._json.user_id;
  }

  /**
   * Get object id.
   * @returns {string}
   */
  get objectId(): string {
    return this._json.object_id;
  }

  /**
   * Get first name.
   * @returns {string}
   */
  get firstName(): string {
    return this._json.first_name;
  }

  /**
   * Get last name.
   * @returns {string}
   */
  get lastName(): string {
    return this._json.last_name;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get disable account.
   * @returns {boolean}
   */
  get disableAccount(): boolean {
    return this._json.disable_account;
  }

  /**
   * Get password.
   * @returns {string}
   */
  get password(): string {
    return this._json.password;
  }

  /**
   * Get password never expires.
   * @returns {boolean}
   */
  get passwordNeverExpires(): boolean {
    return this._json.password_never_expires;
  }

  /**
   * Get change pwd on next login.
   * @returns {boolean}
   */
  get changePwdOnNextLogin(): boolean {
    return this._json.change_pwd_on_next_login;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeSslVpnUserJson}
   */
  get json(): EdgeSslVpnUserJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
