import { EdgeSslVpnPrivateNetworkUpdateRequestJson } from './__json__/edge-ssl-vpn-private-network-update-request-json';

/* istanbul ignore next: autogenerated */
export class EdgeSslVpnPrivateNetworkUpdateRequest {

  private readonly _json: EdgeSslVpnPrivateNetworkUpdateRequestJson;

  constructor(edgeSslVpnPrivateNetworkUpdateRequest: EdgeSslVpnPrivateNetworkUpdateRequest);
  constructor(edgeSslVpnPrivateNetworkUpdateRequestJson: EdgeSslVpnPrivateNetworkUpdateRequestJson);
  constructor(enabled: boolean, description: string, network: string, ports: string, optimize: boolean);
  constructor(firstParam: boolean | EdgeSslVpnPrivateNetworkUpdateRequest | EdgeSslVpnPrivateNetworkUpdateRequestJson,
              description?: string, network?: string, ports?: string, optimize?: boolean) {
    if (typeof firstParam === 'boolean') {
      // Parameters constructor
      this._json = {
        enabled: firstParam,
        description: description,
        network: network,
        ports: ports,
        optimize: optimize
      } as EdgeSslVpnPrivateNetworkUpdateRequestJson;
    } else if (firstParam instanceof EdgeSslVpnPrivateNetworkUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as EdgeSslVpnPrivateNetworkUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as EdgeSslVpnPrivateNetworkUpdateRequestJson;
    }
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get network.
   * @returns {string}
   */
  get network(): string {
    return this._json.network;
  }

  /**
   * Get ports.
   * @returns {string}
   */
  get ports(): string {
    return this._json.ports;
  }

  /**
   * Get optimize.
   * @returns {boolean}
   */
  get optimize(): boolean {
    return this._json.optimize;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeSslVpnPrivateNetworkUpdateRequestJson}
   */
  get json(): EdgeSslVpnPrivateNetworkUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
