import { EdgeSslVpnServiceJson } from './__json__/edge-ssl-vpn-json';
import { EdgeSslVpnAuthentication } from './edge-ssl-vpn-authentication';
import { EdgeSslVpnClientInstallPackage } from './edge-ssl-vpn-client-install-package';
import { EdgeSslVpnIpPool } from './edge-ssl-vpn-ip-pool';
import { EdgeSslVpnLocalAuthenticationServer } from './edge-ssl-vpn-local-authentication-server';
import { EdgeSslVpnPrivateNetwork } from './edge-ssl-vpn-private-network';
import { EdgeSslVpnUser } from './edge-ssl-vpn-user';

/**
 * EdgeSslVpnService class
 */
/* istanbul ignore next: autogenerated */
export class EdgeSslVpnService {

  constructor(private _json: EdgeSslVpnServiceJson) {
  }

  /**
   * Get edge uuid.
   * @returns {string}
   */
  get edgeUuid(): string {
    return this._json.edge_uuid;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get log enabled.
   * @returns {boolean}
   */
  get logEnabled(): boolean {
    return this._json.log_enabled;
  }

  /**
   * Get log level.
   * @returns {string}
   */
  get logLevel(): string {
    return this._json.log_level;
  }

  /**
   * Get ip.
   * @returns {string}
   */
  get ip(): string {
    return this._json.ip;
  }

  /**
   * Get port.
   * @returns {number}
   */
  get port(): number {
    return this._json.port;
  }

  /**
   * Get cipher list.
   * @returns {Array<string>}
   */
  get cipherList(): Array<string> {
    return this._json.cipher_list;
  }

  /**
   * Get private networks.
   * @returns {Array<EdgeSslVpnPrivateNetwork>}
   */
  get privateNetworks(): Array<EdgeSslVpnPrivateNetwork> {
    return this._json.private_networks.map((network) => new EdgeSslVpnPrivateNetwork(network));
  }

  /**
   * Get users.
   * @returns {Array<EdgeSslVpnUser>}
   */
  get users(): Array<EdgeSslVpnUser> {
    return this._json.users.map((user) => new EdgeSslVpnUser(user));
  }

  /**
   * Get ip pools.
   * @returns {Array<EdgeSslVpnIpPool>}
   */
  get ipPools(): Array<EdgeSslVpnIpPool> {
    return this._json.ip_pools.map((pool) => new EdgeSslVpnIpPool(pool));
  }

  /**
   * Get client install packages.
   * @returns {Array<EdgeSslVpnClientInstallPackage>}
   */
  get clientInstallPackages(): Array<EdgeSslVpnClientInstallPackage> {
    return this._json.client_install_packages.map((data) => new EdgeSslVpnClientInstallPackage(data));
  }

  /**
   * Get authentication config.
   * @returns {EdgeSslVpnLocalAuthenticationServerJson}
   */
  get authenticationConfig(): EdgeSslVpnLocalAuthenticationServer {
    return new EdgeSslVpnLocalAuthenticationServer(this._json.authentication_config);
  }

  /**
   * Get authentication.
   * @returns {EdgeSslVpnAuthentication}
   */
  get authentication(): EdgeSslVpnAuthentication {
    return new EdgeSslVpnAuthentication(this._json.authentication);
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeSslVpnServiceJson}
   */
  get json(): EdgeSslVpnServiceJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
