import { EdgeSslVpnAuthServerType } from './__json__/edge-ssl-vpn-auth-server-type';
import { EdgeSslVpnAuthenticationServerJson } from './__json__/edge-ssl-vpn-json';

/**
 * EdgeSslVpnAuthenticationServer class.
 */
/* istanbul ignore next: autogenerated */
export class EdgeSslVpnAuthenticationServer {

  constructor(protected _json: EdgeSslVpnAuthenticationServerJson) {
  }

  /**
   * Get type.
   * @returns {EdgeSslVpnAuthServerType}
   */
  get type(): EdgeSslVpnAuthServerType {
    return this._json.type;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeSslVpnAuthenticationServerJson}
   */
  get json(): EdgeSslVpnAuthenticationServerJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
