import { EdgeSslVpnIpPoolUpdateRequestJson } from './__json__/edge-ssl-vpn-ip-pool-update-request-json';

/* istanbul ignore next: autogenerated */
export class EdgeSslVpnIpPoolUpdateRequest {

  private readonly _json: EdgeSslVpnIpPoolUpdateRequestJson;

  constructor(edgeSslVpnIpPoolUpdateRequest: EdgeSslVpnIpPoolUpdateRequest);
  constructor(edgeSslVpnIpPoolUpdateRequestJson: EdgeSslVpnIpPoolUpdateRequestJson);
  constructor(description: string, ipRange: string, netmask: string, gateway: string, primaryDns: string,
              secondaryDns: string, dnsSuffix: string, winsServer: string, enabled: boolean);
  constructor(firstParam: string | EdgeSslVpnIpPoolUpdateRequest | EdgeSslVpnIpPoolUpdateRequestJson,
              ipRange?: string, netmask?: string, gateway?: string, primaryDns?: string, secondaryDns?: string,
              dnsSuffix?: string, winsServer?: string, enabled?: boolean) {
    if (typeof firstParam === 'string') {
      // Parameters constructor
      this._json = {
        description: firstParam,
        ip_range: ipRange,
        netmask: netmask,
        gateway: gateway,
        primary_dns: primaryDns,
        secondary_dns: secondaryDns,
        dns_suffix: dnsSuffix,
        wins_server: winsServer,
        enabled: enabled
      } as EdgeSslVpnIpPoolUpdateRequestJson;
    } else if (firstParam instanceof EdgeSslVpnIpPoolUpdateRequest) {
      // Copy constructor
      this._json = (firstParam as EdgeSslVpnIpPoolUpdateRequest).json;
    } else {
      // Json or empty constructor
      this._json = (firstParam || {}) as EdgeSslVpnIpPoolUpdateRequestJson;
    }
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get ip range.
   * @returns {string}
   */
  get ipRange(): string {
    return this._json.ip_range;
  }

  /**
   * Get netmask.
   * @returns {string}
   */
  get netmask(): string {
    return this._json.netmask;
  }

  /**
   * Get gateway.
   * @returns {string}
   */
  get gateway(): string {
    return this._json.gateway;
  }

  /**
   * Get primary dns.
   * @returns {string}
   */
  get primaryDns(): string {
    return this._json.primary_dns;
  }

  /**
   * Get secondary dns.
   * @returns {string}
   */
  get secondaryDns(): string {
    return this._json.secondary_dns;
  }

  /**
   * Get dns suffix.
   * @returns {string}
   */
  get dnsSuffix(): string {
    return this._json.dns_suffix;
  }

  /**
   * Get wins server.
   * @returns {string}
   */
  get winsServer(): string {
    return this._json.wins_server;
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeSslVpnIpPoolUpdateRequestJson}
   */
  get json(): EdgeSslVpnIpPoolUpdateRequestJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
