import { EdgeSslVpnPrivateNetworkJson } from './__json__/edge-ssl-vpn-json';

/**
 * EdgeSslVpnPrivateNetwork class
 */
/* istanbul ignore next: autogenerated */
export class EdgeSslVpnPrivateNetwork {

  constructor(private _json: EdgeSslVpnPrivateNetworkJson) {
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get description.
   * @returns {string}
   */
  get description(): string {
    return this._json.description;
  }

  /**
   * Get network.
   * @returns {string}
   */
  get network(): string {
    return this._json.network;
  }

  /**
   * Get ports.
   * @returns {string}
   */
  get ports(): string {
    return this._json.ports;
  }

  /**
   * Get optimize.
   * @returns {boolean}
   */
  get optimize(): boolean {
    return this._json.optimize;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeSslVpnPrivateNetworkJson}
   */
  get json(): EdgeSslVpnPrivateNetworkJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
