import { AuthenticationJson } from './__json__/authentication-json';
import { RoutingAuthenticationType } from './__json__/routing-authentication-type';

/**
 * Authentication
 */
/* istanbul ignore next: autogenerated */
export class Authentication {

  constructor(private _json: AuthenticationJson) {
  }

  /**
   * Get type.
   * @returns {RoutingAuthenticationType}
   */
  get type(): RoutingAuthenticationType {
    return this._json.type;
  }

  /**
   * Get value.
   * @returns {string | undefined}
   */
  get value(): string | undefined {
    return this._json.value || undefined;
  }

  /**
   * Get the json representation of this class.
   * @returns {AuthenticationJson}
   */
  get json(): AuthenticationJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
