import { DefaultRouteJson } from './__json__/default-route-json';

/**
 * Default Route
 */
/* istanbul ignore next: autogenerated */
export class DefaultRoute {

  constructor(private _json: DefaultRouteJson) {
  }

  /**
   * Get description.
   * @returns {string | undefined}
   */
  get description(): string | undefined {
    return this._json.description || undefined;
  }

  /**
   * Get type.
   * @returns {string | undefined}
   */
  get type(): string | undefined {
    return this._json.type || undefined;
  }

  /**
   * Get mtu.
   * @returns {number}
   */
  get mtu(): number {
    return this._json.mtu;
  }

  /**
   * Get vnic.
   * @returns {number}
   */
  get vnic(): number {
    return this._json.vnic;
  }

  /**
   * Get gateway address.
   * @returns {string}
   */
  get gatewayAddress(): string {
    return this._json.gateway_address;
  }

  /**
   * Get admin distance.
   * @returns {number}
   */
  get adminDistance(): number {
    return this._json.admin_distance;
  }

  /**
   * Get the json representation of this class.
   * @returns {DefaultRouteJson}
   */
  get json(): DefaultRouteJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
