import { IpPrefixJson } from './__json__/ip-prefix-json';

/**
 * IP Prefix
 */
/* istanbul ignore next: autogenerated */
export class IpPrefix {

  constructor(private _json: IpPrefixJson) {
  }

  /**
   * Get name.
   * @returns {string}
   */
  get name(): string {
    return this._json.name;
  }

  /**
   * Get ip address.
   * @returns {string}
   */
  get ipAddress(): string {
    return this._json.ip_address;
  }

  /**
   * Get ge.
   * @returns {number}
   */
  get ge(): number {
    return this._json.ge;
  }

  /**
   * Get le.
   * @returns {number}
   */
  get le(): number {
    return this._json.le;
  }

  /**
   * Get the json representation of this class.
   * @returns {IpPrefixJson}
   */
  get json(): IpPrefixJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
