import { OSPFAreaJson } from './__json__/ospf-area-json';
import { RoutingAreaType } from './__json__/routing-area-type';
import { Authentication } from './authentication';

/**
 * OSPF Area
 */
/* istanbul ignore next: autogenerated */
export class OSPFArea {

  constructor(private _json: OSPFAreaJson) {
  }

  /**
   * Get area id.
   * @returns {number}
   */
  get areaId(): number {
    return this._json.area_id;
  }

  /**
   * Get type.
   * @returns {RoutingAreaType}
   */
  get type(): RoutingAreaType {
    return this._json.type;
  }

  /**
   * Get authentication.
   * @returns {Authentication}
   */
  get authentication(): Authentication {
    return new Authentication(this._json.authentication);
  }

  /**
   * Get translate type 7 to type 5.
   * @returns {boolean | undefined}
   */
  get translateType7ToType5(): boolean | undefined {
    return this._json.translate_type_7_to_type_5 || undefined;
  }

  /**
   * Get the json representation of this class.
   * @returns {OSPFAreaJson}
   */
  get json(): OSPFAreaJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
