import { VacPerfSampleJson } from './__json__/vac-perf-sample';

/* istanbul ignore next: autogenerated */
export class VacPerfSample {

  constructor(private _json: VacPerfSampleJson) {
  }

  /**
   * Get used quota.
   * @returns {number}
   */
  get usedQuota(): number {
    return this._json.used_quota;
  }

  /**
   * Get quota.
   * @returns {number}
   */
  get quota(): number {
    return this._json.quota;
  }

  /**
   * Get time.
   * @returns {number}
   */
  get time(): number {
    return this._json.time;
  }

  /**
   * Get the json representation of this class.
   * @returns {VacPerfSampleJson}
   */
  get json(): VacPerfSampleJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
