import { DiskCostAndUsageJson } from './__json__/disk-cost-and-usage-json';
import { ResourceCostAndUsage } from './resource-cost-and-usage';

/* istanbul ignore next: autogenerated */
export class DiskCostAndUsage {

  constructor(private _json: DiskCostAndUsageJson) {
  }

  /**
   * Get total.
   * @returns {ResourceCostAndUsage}
   */
  get total(): ResourceCostAndUsage {
    return new ResourceCostAndUsage(this._json.total);
  }

  /**
   * Get hdd.
   * @returns {ResourceCostAndUsage}
   */
  get hdd(): ResourceCostAndUsage {
    return new ResourceCostAndUsage(this._json.hdd);
  }

  /**
   * Get ssd.
   * @returns {ResourceCostAndUsage}
   */
  get ssd(): ResourceCostAndUsage {
    return new ResourceCostAndUsage(this._json.ssd);
  }

  /**
   * Get archive.
   * @returns {ResourceCostAndUsage}
   */
  get archive(): ResourceCostAndUsage {
    return new ResourceCostAndUsage(this._json.archive);
  }

  /**
   * Get the json representation of this class.
   * @returns {DiskCostAndUsageJson}
   */
  get json(): DiskCostAndUsageJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
