import { ProtectionSource } from '../backup-group/protection-source';
import { CopyRunStats } from './copy-run-stats';
import { CopySnapshotTaskStatusJson } from './__json__/copy-snapshot-task-status-json';
import { StatusCopySnapshotTaskStatus } from './__json__/status-copy-snapshot-task-status';

/**
 * Copy Snapshot Task Status.
 */
/* istanbul ignore next: autogenerated */
export class CopySnapshotTaskStatus {

  constructor(private _json: CopySnapshotTaskStatusJson) {
  }

  /**
   * Get error.
   * @returns {string | null}
   */
  get error(): string | null {
    return this._json.error || null;
  }

  /**
   * Get source.
   * @returns {ProtectionSource}
   */
  get source(): ProtectionSource {
    return new ProtectionSource(this._json.source);
  }

  /**
   * Get stats.
   * @returns {CopyRunStats}
   */
  get stats(): CopyRunStats {
    return new CopyRunStats(this._json.stats);
  }

  /**
   * Get status.
   * @returns {StatusCopySnapshotTaskStatus}
   */
  get status(): StatusCopySnapshotTaskStatus {
    return this._json.status;
  }

  /**
   * Get task end time.
   * @returns {number | null}
   */
  get taskEndTime(): number | null {
    return this._json.task_end_time ?? null;
  }

  /**
   * Get task start time.
   * @returns {number}
   */
  get taskStartTime(): number {
    return this._json.task_start_time;
  }

  /**
   * Get the json representation of this class.
   * @returns {CopySnapshotTaskStatusJson}
   */
  get json(): CopySnapshotTaskStatusJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
