import { ArchivalExternalTarget } from '../backup-policy/archival-external-target';
import { ReplicationTargetSettings } from '../backup-policy/replication-target-settings';
import { SnapshotTargetSettingsJson } from './__json__/snapshot-target-settings-json';
import { SnapshotTargetType } from './__json__/snapshot-target-type';

/**
 * Snapshot Target Settings.
 */
/* istanbul ignore next: autogenerated */
export class SnapshotTargetSettings {

  constructor(private _json: SnapshotTargetSettingsJson) {
  }

  /**
   * Get archival target.
   * @returns {ArchivalExternalTarget | null}
   */
  get archivalTarget(): ArchivalExternalTarget | null {
    return this._json.archival_target ? new ArchivalExternalTarget(this._json.archival_target) : null;
  }

  /**
   * Get replication target.
   * @returns {ReplicationTargetSettings | null}
   */
  get replicationTarget(): ReplicationTargetSettings | null {
    return this._json.replication_target ? new ReplicationTargetSettings(this._json.replication_target) : null;
  }

  /**
   * Get type.
   * @returns {SnapshotTargetType}
   */
  get type(): SnapshotTargetType {
    return this._json.type;
  }

  /**
   * Get the json representation of this class.
   * @returns {SnapshotTargetSettingsJson}
   */
  get json(): SnapshotTargetSettingsJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
